### ISSUE TITLE
C48 ufs_model run fails because C48.mx100_frac does not exist

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/global-workflow#686] opened 2022-03-22 13:58 UTC
**Expected behavior**
C48L127 ufs_model should run

**Current behavior**
C48L127 ufs_model fails because an expected input fix file can not be found.

**Machines affected**
Failure occurred on Orion, but is likely to occur on other machines if expected fix directory is not present.

**To Reproduce**
Run efcs (or fcst) at C48.   

**Context**
Should the `C48` line in `config.efcs` set `OCNRES` to `400` or do we need to create and populate `/work/noaa/global/glopara/fix_NEW/fix_fv3_fracoro\C48.mx100_frac`?

**Detailed Description**
Check `/work/noaa/stmp/rtreadon/comrot/prgsida/logs/2021122300/gdasefcs01.log` and search for 
```
 6:
 6: FATAL from PE     6: Error with opening file INPUT/oro_data.nc
 6:
10:
10: FATAL from PE    10: Error with opening file INPUT/oro_data.nc
10:
```
Scrolling back in the log file, we find
```
2 + '[' .true. = .true. ']'
2 + OROFIX=/work/noaa/da/Russ.Treadon/git/global_workflow/ufsda/fix/fix_fv3_fracoro/C48.mx100_frac
2 + FIX_SFC=/work/noaa/da/Russ.Treadon/git/global_workflow/ufsda/fix/fix_fv3_fracoro/C48.mx100_frac/fix_sfc
22 + seq 1 6
2 + for n in '$(seq 1 $ntiles)'
2 + /bin/ln -sf /work/noaa/da/Russ.Treadon/git/global_workflow/ufsda/fix/fix_fv3_fracoro/C48.mx100_frac/oro_C48.mx100.tile1.nc /wo\
rk/noaa/stmp/rtreadon/RUNDIRS/prgsida/2021122300/gdas/efcs.79540/mem001/INPUT/oro_data.tile1.nc
```
File `/work/noaa/da/Russ.Treadon/git/global_workflow/ufsda/fix/fix_fv3_fracoro/C48.mx100_frac/oro_C48.mx100.tile3.nc` does not exist.  Directory `/work/noaa/da/Russ.Treadon/git/global_workflow/ufsda/fix/fix_fv3_fracoro/` is a soft link to `/work/noaa/global/glopara/fix_NEW/fix_fv3_fracoro`.    This directory contains 
```
drwxr-sr-x 3 kfriedma global 4096 May 18  2021 C192.mx050_frac
drwxr-sr-x 3 kfriedma global 4096 May 18  2021 C384.mx025_frac
drwxr-sr-x 3 kfriedma global 4096 Aug 23  2021 C48.mx400_frac
drwxr-sr-x 3 kfriedma global 4096 May 18  2021 C768.mx025_frac
drwxr-sr-x 3 kfriedma global 4096 May 18  2021 C96.mx100_frac
```
Directory `C48.mx100_frac` is not present.

A check of `config.efcs` finds the following logic
```
# ocean model resolution
case "$CASE_ENKF" in
    "C48") export OCNRES=100;;
    "C96") export OCNRES=100;;
    "C192") export OCNRES=050;;
    "C384") export OCNRES=025;;
    "C768") export OCNRES=025;;
    *) export OCNRES=025;;
esac
```
The failed efcs job ran in `/work/noaa/stmp/rtreadon/RUNDIRS/prgsida/2021122300/gdas/efcs.301701`.   Execution of ufs_model failed for all 10 membes in efcs01.

**Additional Information**
This low resolution GSI-GDAS parallel is the control for a low resolution JEDI-GDAS test.   Both the GSI and JEDI based DA systems use the same forecast model and face the same problem.  This problem needs to be resolved in order for both parallels to cycle forward.

**Possible Implementation**
Two possible solutions:
1. Replace `OCNRES=100` with `OCNRES=400` on the `C48` line in `config.efcs`.  A similar change is required on the `C48` line in `config.base` and `config.base.emc.dyn`.  
2. Add and populate a new fix directory, `C48.mx100_frac`, in  `/work/noaa/global/glopara/fix_NEW/fix_fv3_fracoro`.   If a new directory is created and populated, this new directory needs to be added on all machines supported by the global-workflow.

**Comment by WalterKolczynski-NOAA** [comment] 2022-03-22 14:19
Duplicate of #650. There's already a PR fixing this (#651), but it has been languishing. I'm going to try to push it along. But the fix is pretty small.

**Closed as completed by WalterKolczynski-NOAA** 2022-03-22 14:19 UTC
Labels: bug, duplicate
