### ISSUE TITLE
gfs_atmos_gempak_meta silent fail

### ISSUE THREAD

**Issue by lgannoaa** [NOAA-EMC/global-workflow#599] opened 2022-01-19 16:36 UTC
Silent fail found in gfs gempak meta job. Here is the ecflow job log from NCO wcoss2 para:
```
/lfs/h1/ops/para/output/20220116/gfs_atmos_gempak_meta_00.o526230 (line 2068)
/lfs/h1/ops/para/packages/gfs.v16.2.0/scripts/exgfs_atmos_gempak_meta.sh[86]: [: argument expected
grep "argument expected" gfs_atmos_gempak_meta_00.o526230
/lfs/h1/ops/para/packages/gfs.v16.2.0/scripts/exgfs_atmos_gempak_meta.sh[86]: [: argument expected
/lfs/h1/ops/para/packages/gfs.v16.2.0/scripts/exgfs_atmos_gempak_meta.sh[111]: [: argument expected
/lfs/h1/ops/para/packages/gfs.v16.2.0/scripts/exgfs_atmos_gempak_meta.sh[130]: [: argument expected
```

This issue also exist in current operation:
```
[Lin.Gan@v71a1 today]$ pwd
/gpfs/dell1/nco/ops/com/output/prod/today
[Lin.Gan@v71a1 today]$ grep "argument expected" gfs_atmos_gempak_meta_.o
gfs_atmos_gempak_meta_00.o82082149:/gpfs/dell1/nco/ops/nwprod/gfs.v16.1.5/scripts/exgfs_atmos_gempak_meta.sh[88]: [: argument expected
gfs_atmos_gempak_meta_00.o82082149:/gpfs/dell1/nco/ops/nwprod/gfs.v16.1.5/scripts/exgfs_atmos_gempak_meta.sh[113]: [: argument expected
gfs_atmos_gempak_meta_00.o82082149:/gpfs/dell1/nco/ops/nwprod/gfs.v16.1.5/scripts/exgfs_atmos_gempak_meta.sh[134]: [: argument expected
gfs_atmos_gempak_meta_06.o82101027:/gpfs/dell1/nco/ops/nwprod/gfs.v16.1.5/scripts/exgfs_atmos_gempak_meta.sh[88]: [: argument expected
gfs_atmos_gempak_meta_06.o82101027:/gpfs/dell1/nco/ops/nwprod/gfs.v16.1.5/scripts/exgfs_atmos_gempak_meta.sh[113]: [: argument expected
gfs_atmos_gempak_meta_06.o82101027:/gpfs/dell1/nco/ops/nwprod/gfs.v16.1.5/scripts/exgfs_atmos_gempak_meta.sh[134]: [: argument expected
gfs_atmos_gempak_meta_12.o82121227:/gpfs/dell1/nco/ops/nwprod/gfs.v16.1.5/scripts/exgfs_atmos_gempak_meta.sh[88]: [: argument expected
gfs_atmos_gempak_meta_12.o82121227:/gpfs/dell1/nco/ops/nwprod/gfs.v16.1.5/scripts/exgfs_atmos_gempak_meta.sh[113]: [: argument expected
gfs_atmos_gempak_meta_12.o82121227:/gpfs/dell1/nco/ops/nwprod/gfs.v16.1.5/scripts/exgfs_atmos_gempak_meta.sh[134]: [: argument expected
```

**Expected behavior**

No silent fail is expected.
**Current behavior**

Has silent fail.
**Machines affected**

Current operation GFS in Dell and wcoss2 NCO para.
**To Reproduce**

Run the job with normal condition.
**Context**

**Detailed Description**

See description above.
**Additional Information**

No additional information.
**Possible Implementation**

Fix is needed.

**Comment by WalterKolczynski-NOAA** [comment] 2022-01-19 16:38
Is there an actual failure, or just a warning? The shell code is littered with undefined variables that pop warnings like this but don't impact the output (at least, for normal usage).

Should be fixed either way, but has a big impact in how we triage it.

**Comment by lgannoaa** [comment] 2022-01-19 16:41
This issue is open on request from Wei Wei.

**Comment by WalterKolczynski-NOAA** [comment] 2022-01-19 16:42
Also, please copy any output files (especially those from ops) into a [gist](https://gist.github.com/) and link to the gist, rather than relying on paths that might change.

**Comment by BoiVuong-NOAA** [comment] 2022-01-19 17:36
Hi WalterKolczynski, 
It is just a warning.  The job (JGFS_ATMOS_GEMPAK_META) has passed i the variable to the script
#find out what fcst hr to start processing
fhr=$fhend      where  fhend=384 forecast hour
The condition check for variable fhr is to prevent the job needs to rerun an entire of all forecast hours (384) or just to rerun at the forecast hour that requested.   The job still produce the gempak meta files as same in operational.

**Comment by BoiVuong-NOAA** [comment] 2022-01-19 20:29
I reconstructed the job (gfs_atmos_gempak_meta) and used Lin's input gempak files from:
 COMIN=/lfs/h2/emc/ptmp/Lin.Gan/ecfops/com/para/gfs/v16.2/gfs.20211227/00/atmos/gempak.
The gempak meta job run fine and all output gempak meta files are correct.

**Comment by arunchawla-NOAA** [comment] 2022-01-27 21:45
Is this still an issue ? @lgannoaa since you reported it can you provide a fix and confirm that the silent failure is gone?

**Comment by lgannoaa** [comment] 2022-01-27 21:54
@arunchawla-NOAA looking at the current wcoss2 NCO testing, it is still showing argument expected in job log:
/lfs/h1/ops/para/output/20220127/gfs_atmos_gempak_meta_00.o1109892
Lin.Gan@ddecflow02:/lfs/h1/ops/para/output/20220127> grep "argument expected" gfs_atmos_gempak_meta_00.o1109892                         
/lfs/h1/ops/para/packages/gfs.v16.2.0/scripts/exgfs_atmos_gempak_meta.sh[86]: [: argument expected
/lfs/h1/ops/para/packages/gfs.v16.2.0/scripts/exgfs_atmos_gempak_meta.sh[111]: [: argument expected
/lfs/h1/ops/para/packages/gfs.v16.2.0/scripts/exgfs_atmos_gempak_meta.sh[130]: [: argument expected
I will take a look.

**Comment by WalterKolczynski-NOAA** [comment] 2022-01-27 21:57
@arunchawla-NOAA this is a broader issue than what is here. This should probably just be marked as a duplicate of #397. Once we turn on checks for uninitialized variables, this sort of thing will be weeded out.

**Comment by arunchawla-NOAA** [comment] 2022-01-27 21:59
OK, if it is covered in #397 then suggest closing this then ? Unless you want to capture the information here

**Comment by lgannoaa** [comment] 2022-01-27 22:14
@arunchawla-NOAA I was research for the solution and working on this issue. @WalterKolczynski-NOAA closed it without my input.

**Comment by arunchawla-NOAA** [comment] 2022-01-27 22:27
@lgannoaa I asked him to since it is a duplicate of #397. We should decide if that needs to be elevated to clean up our scripts

**Comment by lgannoaa** [comment] 2022-01-27 22:45
Looks like this issue is caused by exgfs_atmos_gempak_meta.sh script use wrong syntax in statement typeset -Z2 fhr.
This is not a unassigned variable issue. 
Code typeset -Z2 fhr works when $fhr is a number. It will not work as desired if $fhr is a string.
Still need time to research for detail and solution to fix it. @arunchawla-NOAA do you still want this issue to be closed?

**Comment by WalterKolczynski-NOAA** [comment] 2022-01-27 22:53
It seems like it is technically still an undefined variable issue, just one caused internally. printf should be used in place of typeset and the statements should be taken out of if-blocks.

I've added an item to #397 to make sure we are always using printf consistently, but I've reopened this issue if we want to fix just this instance more immediately.

**Comment by lgannoaa** [comment] 2022-01-27 23:07
@BoiVuong-NOAA 
Please take a look at exgfs_atmos_gempak_meta.sh and let us know why line 74 do the typeset on a string?
1. This error resulting line 87 not been executed. Can we remove the use of typeset with a workaround that is safe? Maybe implement a check before typeset to ensure the variable type is desired if no available workaround?
2. If line 87 is not need can you double check and remove it as necessary?
3. Please see the same for the other two similar issue in this script.

Reference log on prod:
/gpfs/dell1/nco/ops/com/output/prod/today/gfs_atmos_gempak_meta_00.o82695226
wcoss2 nco ecflow test:
/lfs/h1/ops/para/output/20220127/gfs_atmos_gempak_meta_00.o1109892

Thanks

**Comment by BoiVuong-NOAA** [comment] 2022-01-28 02:01
@lgannoaa 
You can change this line in the script exgfs_atmos_gempak_meta.sh as below:
export fhr    ---->   export fhr=$fhr
Note: The JGFS_ATMOS_GEMPAK_META should run after JGFS_ATMOS_GEMPAK_META job is finished.
I ran the same job with all gempak files  from your  COMIN=/lfs/h1/ops/para/com/gfs/v16.2/gfs.20211227/00/atmos/gempak
and the job ran fine and all output gempak meta files are same as your output in COMOUT=/lfs/h1/ops/para/com/gfs/v16.2/gfs.20211227/00/atmos/gempak/meta.  





I found that the script exgfs_atmos_gempak_meta.sh needs to change

**Comment by BoiVuong-NOAA** [comment] 2022-01-28 02:45
I have modified the script exgfs_atmos_gempak_meta.sh and tested with NCO data at exgfs_atmos_gempak_meta.sh.
You can pick up this script at: /lfs/h2/emc/vpppg/noscrub/Boi.Vuong/lin
Would you try to run it with your ecflow ? Please let me know if you see any issues.
Note: The JGFS_ATMOS_GEMPAK_META should run after JGFS_ATMOS_GEMPAK job is finished.

**Comment by KateFriedman-NOAA** [comment] 2022-01-28 15:12
Tagging @WeiWei-NCO for his knowledge

**Comment by BoiVuong-NOAA** [comment] 2022-01-28 15:19
Thanks, Kate.

**Comment by KateFriedman-NOAA** [comment] 2022-01-28 17:11
After speaking to @WeiWei-NCO I have pulled @BoiVuong-NOAA's modified copy of `exgfs_atmos_gempak_meta.sh` into `feature/ops-wcoss2` at 53b101e0.

Any further work for this issue or may I close it? Thanks!

**Closed as completed** 2022-01-28 20:16 UTC
Labels: bug, duplicate
