### ISSUE TITLE
C384L127 FV3_GFS_v17_p8 ufs_model.x fails

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/global-workflow#1695] opened 2023-06-15 15:27 UTC
**Expected behavior**
The FV3_GFS_v17_p8 `ufs_model.x` should run to completion on Hera at C384L127.

**Current behavior**
C384L127 gdasfcst job aborts on Hera with
```
280: slurmstepd: error: Detected 1 oom-kill event(s) in StepId=46030512.0. Some of your processes may have been killed by the cgroup out-of-memory handler.
srun: error: h32m33: task 302: Out Of Memory
srun: launch/slurm: _step_signal: Terminating StepId=46030512.0
  0: slurmstepd: error: *** STEP 46030512.0 ON h32m01 CANCELLED AT 2023-06-15T13:48:38 ***
```

**Machines affected**
Only tested on Hera

**To Reproduce**
1. clone g-w `develop` at [173a25b](https://github.com/NOAA-EMC/global-workflow/commit/173a25bd6d6afdf2be5f3fe3541b7c6ccc0d8e59)
2. execute `sorc/checout.sh`, `build_all.sh`, and `link_workflow.sh`
3. set up `EXPDIR`
4. populate `ROTDIR` with files need for C384L127 gdasfcst
5. rocotoboot gdasfcst

**Additional Information**
Notice that  the C384 section of `config.ufs` specifies 2 threads to gfs fcst.
```
        export nthreads_fv3=1
        export nthreads_fv3_gfs=2
```
As a test change `nthreads_fv3=2`, regenerate xml, and reboot gdasfcst.   `ufs_model.x` ran to completion.  

When 2 threads are specified the gdasfcst xml reads
```
        <nodes>20:ppn=40:tpp=1</nodes>
```
This is 20 x 40 = 800 tasks.   The successful gdasfcst job runs `ufs_model.x` with
```
+ exglobal_forecast.sh[182]: srun -l --export=ALL -n 800 /scratch2/NCEPDEV/stmp1/role.jedipara/RUNDIRS/pratmos/fcst.244399/ufs_model.x
```
In contrast, when `nthreads_fv3=`, the xml specifies
```
        <nodes>10:ppn=40:tpp=1</nodes>
```
This is 10 x 40 = 400 tasks.   The failed gdasfcst job runs `ufs_model.x` with 
```
+ exglobal_forecast.sh[182]: srun -l --export=ALL -n 400 /scratch2/NCEPDEV/stmp1/role.jedipara/RUNDIRS/pratmos/fcst.53132/ufs_model.x
```

The `<nodes>20:ppn=40:tpp=1</nodes>` setting seems odd when `nthreads_fv3=2`.   Shouldn't two threads be `tpp=2` in the xml file?

I don't think setting `nthreads_fv3=2` is the correct solution ... even it the model runs with this.

**Comment by RussTreadon-NOAA** [comment] 2023-06-15 15:32
This issue may be related to g-w issue #1664.

**Comment by JessicaMeixner-NOAA** [comment] 2023-06-15 17:06
@RussTreadon-NOAA I believe the reason that the tppn=1 remains as is even though you changed the fv3 threads is because the global workflow has moved to using ESMF managed threading.  This allows ESMF to manage the threading, so even though tppn=40, FV3 should be given 2 threads from ESMF.

**Comment by RussTreadon-NOAA** [comment] 2023-06-15 17:09
@JessicaMeixner-NOAA, thank you for the explanation.  Good to know that the xml is OK.  I should have believed the comment `# ESMF handles threading for the UFS-weather-model` in `config.resources`.

**Comment by WalterKolczynski-NOAA** [comment] 2023-06-15 17:16
Closing as duplicate of #1572

**Closed as not planned by WalterKolczynski-NOAA** 2023-06-15 17:16 UTC
Labels: bug
