### ISSUE TITLE
Placeholder for tracking WCOSS2 Forecast Job Hanging Issues 

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#1845] opened 2023-09-11 15:07 UTC
### What new functionality do you need?

Many forecast jobs running the HR2 tag on WCOSS2 have hung.  This issue was decreased by not eliminated by adding the following environment variables recommended by GDIT: 
export MPICH_ENV_DISPLAY=1
export MPICH_VERSION_DISPLAY=1
export FI_MR_CACHE_MONITOR=memhooks

It's also been suggested to try adding: 
export FI_MR_CACHE_MONITOR=memhooks

There is an open issue from @jiandewang with GDIT about this problem. 

Lastly, @junwang-noaa suggests updating to the latest HDF5 libraries which would require updating the hash of ufs-waether-model that's being used in global-workflow. 

This issue has been created to track the possible need of adding these variables to the forecast job for WCOSS2 (particularly when running C768, I'm unaware of issues at lower resolution).  It's not 100% clear if these are needed at this time, although they're highly recommend if you are running the HR2 tag & C768 resolution on WCOSS2. 

 

### What are the requirements for the new functionality?

C768 S2SW GFS forecast jobs do not hang. 

### Acceptance Criteria

C768 S2SW GFS forecast jobs do not hang.

**Comment by KateFriedman-NOAA** [comment] 2023-09-11 15:15
@JessicaMeixner-NOAA Have you spoken with GDIT about the hangs? I investigated a similar issue with them (late 2022 into early 2023) after hangs started with the enkf forecast jobs in both production and development tests (C384). We didn't find a root cause but the hangs seemed to stop after some machine upgrades. Some hangs were traced to hardware issues but not every one.

Interesting to see it in C768 now and that those environment variables help some. GDIT could assist to investigate further if you haven't already opened a helpdesk ticket. :)

**Comment by JessicaMeixner-NOAA** [comment] 2023-09-11 15:16
Yes, apologies I deleted that these were from GDIT as I edited the issue.  I'll add that back in.

**Comment by KateFriedman-NOAA** [comment] 2023-09-11 15:17
Great! Upgrading to the newer HDF5 (as Jun suggested) should hopefully also help (GDIT and George V suggested something similar during investigations). Look forward to the new version!

**Comment by jiandewang** [comment] 2023-11-02 02:44
with many tests, Jun and I confirm that by add "ucx" modules the hanging issue is gone.
    module load craype-network-ucx
    module load cray-mpich-ucx

**Comment by KateFriedman-NOAA** [comment] 2024-01-25 19:50
Checking in...is this resolved and closable? Thanks!

**Comment by JessicaMeixner-NOAA** [comment] 2024-01-25 19:58
The ucx modules resolves are hanging issues and have been added to the workflow.  So in that since I think this can be closed.

**Comment by KateFriedman-NOAA** [comment] 2024-01-25 20:01
Sounds good, closing. Thanks @JessicaMeixner-NOAA !

**Closed as completed by KateFriedman-NOAA** 2024-01-25 20:01 UTC
Labels: feature, triage
