### ISSUE TITLE
Update/correct UPP itag file in develop

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#797] opened 2022-05-18 13:42 UTC
**Description**

Check that the correct itag file is used in offline and in-line post. Update/correct if not. @yangfanglin reported an incorrect number of layers in his experiments.

**Comment by yangfanglin** [comment] 2022-05-18 14:15
The atmospheric "master" files from the experiments I made with the latest coupled global-workflow (as of May 10, 2022) only have 45 isobaric  layers and only up to 2 hPa.   The current operation GFS has 57 layers up to 0.01 hPa.

With the help from @WenMeng-NOAA , we found post_tag_gfs128 in the global workflow ./parm/post directory is missing the following namelist 

&MODEL_INPUTS 
MODELNAME='GFS'

BTW, ufs_model.fd/tests/parm/post_itag is up to date.  Therefore, either link_workflow.sh or forecast_postdet.sh should be updated to point to the correct itag

**Comment by WenMeng-NOAA** [comment] 2022-05-18 16:15
There are some recent updates for unifying FV3 interfaces for global and regional in off-line post at the UPP repository and in-line post at the ufs-weather-model repository. It appears to me the ufs version and upp version are not up to date.

**Comment by WenMeng-NOAA** [comment] 2022-05-18 16:19
@yangfanglin I didn't realize post_tag_gfs128 was maintained in UPP repository. I will submit an UPP PR for that update. To reflect that change, upp version checked out in the g-w should be updated.

**Comment by WenMeng-NOAA** [comment] 2022-05-18 23:40
@KateFriedman-NOAA and @WalterKolczynski-NOAA The UPP develop branch was just committed at fbd41a5 for updating post_tag_gfs128 (See [here](https://github.com/NOAA-EMC/UPP/pull/508)). This new post_tag_gfs128 doesn't work for the default 
ufs version Prototype-p8b in the g-w. Would you like to proceed this update now or later?

**Comment by WalterKolczynski-NOAA** [comment] 2022-05-20 00:41
I'm still unable to reproduce this error. I just tried with a fresh checkout of develop, making no changes, and my master files are correct:

```
hfe02 atmos/ > ncl_filedump gfs.t06z.master.grb2f006.grb2 | grep lv_ISBL
      lv_ISBL0 = 57
      lv_ISBL6 = 39
      float TMP_P0_L100_GGA0 ( lv_ISBL0, lat_0, lon_0 )
      float SPFH_P0_L100_GGA0 ( lv_ISBL0, lat_0, lon_0 )
      float RH_P0_L100_GGA0 ( lv_ISBL0, lat_0, lon_0 )
      float CLWMR_P0_L100_GGA0 ( lv_ISBL6, lat_0, lon_0 )
      float ICMR_P0_L100_GGA0 ( lv_ISBL6, lat_0, lon_0 )
      float RWMR_P0_L100_GGA0 ( lv_ISBL6, lat_0, lon_0 )
      float SNMR_P0_L100_GGA0 ( lv_ISBL6, lat_0, lon_0 )
      float GRLE_P0_L100_GGA0 ( lv_ISBL6, lat_0, lon_0 )
      float UGRD_P0_L100_GGA0 ( lv_ISBL0, lat_0, lon_0 )
      float VGRD_P0_L100_GGA0 ( lv_ISBL0, lat_0, lon_0 )
      float VVEL_P0_L100_GGA0 ( lv_ISBL0, lat_0, lon_0 )
      float DZDT_P0_L100_GGA0 ( lv_ISBL0, lat_0, lon_0 )
      float ABSV_P0_L100_GGA0 ( lv_ISBL0, lat_0, lon_0 )
      float HGT_P0_L100_GGA0 ( lv_ISBL0, lat_0, lon_0 )
      float TCDC_P0_L100_GGA0 ( lv_ISBL6, lat_0, lon_0 )
      float O3MR_P0_L100_GGA0 ( lv_ISBL0, lat_0, lon_0 )
      float lv_ISBL6 ( lv_ISBL6 )
      float lv_ISBL0 ( lv_ISBL0 )

hfe02 atmos/ > ncl_filedump gfs.t06z.master.grb2f006.grb2 -v lv_ISBL0

<file info cut>

     lv_ISBL0:
  
   1.000       2.000       4.000       7.000       10.00       20.00    
   40.00       70.00       100.0       200.0       300.0       500.0    
   700.0       1000.       1500.       2000.       3000.       4000.    
   5000.       7000.      0.1000E+05  0.1250E+05  0.1500E+05  0.1750E+05
  0.2000E+05  0.2250E+05  0.2500E+05  0.2750E+05  0.3000E+05  0.3250E+05
  0.3500E+05  0.3750E+05  0.4000E+05  0.4250E+05  0.4500E+05  0.4750E+05
  0.5000E+05  0.5250E+05  0.5500E+05  0.5750E+05  0.6000E+05  0.6250E+05
  0.6500E+05  0.6750E+05  0.7000E+05  0.7250E+05  0.7500E+05  0.7750E+05
  0.8000E+05  0.8250E+05  0.8500E+05  0.8750E+05  0.9000E+05  0.9250E+05
  0.9500E+05  0.9750E+05  0.1000E+06
```

**Comment by WenMeng-NOAA** [comment] 2022-05-20 00:50
@WalterKolczynski-NOAA Fanglin is using the latest ufs-develop-model develop branch which has the commit of unified in-line post interface. That new interface face require a format update in UPP itag file.  In his previous experiment, he used the itag file in old format, the in-line interface read wrong PO setting from itag and reset PO  as  default 45 isobaric levels.

**Comment by WalterKolczynski-NOAA** [comment] 2022-05-20 00:58
There should be no expectation global-workflow will work with any UFS version other than the one currently specified in checkout.sh for precisely this reason: UFS namelists keeps changing. This needs to be part of updating the UFS version in g-w. Long-term, we are looking to eliminate checking out a separate UPP version at all. Maybe I'll just accelerate that.

**Comment by WenMeng-NOAA** [comment] 2022-05-20 01:01
The post_tag_gfs128 in global-workflow is linked to UPP.

**Comment by WalterKolczynski-NOAA** [comment] 2022-05-20 01:08
> The post_tag_gfs128 in global-workflow is linked to UPP.

That's not the issue. The issue, as you've explained it, is Fanglin changed the UFS version from what g-w has without updating the UPP version to match. It's not surprising it broke. Which is one of the reasons we want to stop checking out a separate copy of UPP anyway now that one is in UFS.

**Comment by WenMeng-NOAA** [comment] 2022-05-20 01:34
This issue is a typical case of user support provided by our UPP team on gfs post process. I would expect the g-w team takes over 
it when the  transition of gfs post process  workflow is completed.

**Closed as completed** 2022-05-22 20:50 UTC
Labels: maintenance
