### ISSUE TITLE
 gfsvrfy job fails in develop on WCOSS2

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#1947] opened 2023-10-20 22:14 UTC
### What is wrong?

The vrfy job is failing in the free forecast see /lfs/h2/emc/couple/noscrub/jessica.meixner/develop/s2swc48t01dev/COMROOT/s2swc48t01dev/logs/2021032312/ gfsvrfy.log.0

```
+ Unknown[157]: FORT41=storms.gfso.atcf_gen.altg.2021032312
+ Unknown[157]: export FORT41
+ Unknown[158]: cpreq /lfs/h2/emc/couple/noscrub/jessica.meixner/develop/s2swc48t01dev/COMROOT/s2swc48t01dev/gfs.20210323/12//products/atmos/cyclone/genesis_vital/storms.gfso.atcf_gen.altg.2021032312 .
cp: cannot stat '/lfs/h2/emc/couple/noscrub/jessica.meixner/develop/s2swc48t01dev/COMROOT/s2swc48t01dev/gfs.20210323/12//products/atmos/cyclone/genesis_vital/storms.gfso.atcf_gen.altg.2021032312': No such file or directory

-------------------------------------------------------------
-- FATAL ERROR: 'cp /lfs/h2/emc/couple/noscrub/jessica.meixner/develop/s2swc48t01dev/COMROOT/s2swc48t01dev/gfs.20210323/12//products/atmos/cyclone/genesis_vital/storms.gfso.atcf_gen.altg.2021032312 .' was not successful. RETURN CODE 0
-- ABNORMAL EXIT at Fri Oct 20 21:07:20 UTC 2023 on nid001720
-------------------------------------------------------------
```

### What should have happened?

Job succeedes

### What machines are impacted?

WCOSS2

### Steps to reproduce

Case set up: 

APP=S2SWA
PSLOT=s2swc48t03
BASEDIR= < your path here > 
CDUMP=gfs #gfs or gefs
CONFIGDIR=$BASEDIR/global-workflow/parm/config/${CDUMP}
IDATE=2021032312
EDATE=2021032312
RES=48
GFS_CYC=1
COMROT=$BASEDIR/$PSLOT/COMROOT
EXPDIR=$BASEDIR/$PSLOT/EXPDIR

source gw_setup.sh

 ./setup_expt.py ${CDUMP} forecast-only --app $APP --pslot $PSLOT --configdir $CONFIGDIR --idate $IDATE --edate $EDATE --res $RES --gfs_cyc $GFS_CYC --comrot $COMROT --expdir $EXPDIR 

./setup_xml.py $EXPDIR/$PSLOT

### Additional information

This had previously worked, not sure when it broke.

**Comment by WalterKolczynski-NOAA** [comment] 2023-10-23 10:16
This is because the TC tracker scripts were never updated for the COM refactor. See https://github.com/NOAA-EMC/TC_tracker/issues/1 and https://github.com/NOAA-EMC/TC_tracker/pull/2

The issue is masked on the RDHPCS machines because the scripts rely on `err_exit` and that does not work properly on those machines, so the tracker script fails silently (see https://github.com/NOAA-EMC/global-workflow/issues/1283).

@KateFriedman-NOAA We have (and are using) an installation that says `feature-GFSv17_com_reorg`, but the source repo is the authoritative repo which never merged the changes, so it is just another copy of `v1.1.15.5`. Can we pull in the changes from my repo to hopefully fix this until we can get the auth repo updated? It is only script changes so it wouldn't need to rebuild.

**Comment by KateFriedman-NOAA** [comment] 2023-10-23 18:27
> @KateFriedman-NOAA We have (and are using) an installation that says `feature-GFSv17_com_reorg`, but the source repo is the authoritative repo which never merged the changes, so it is just another copy of `v1.1.15.5`. Can we pull in the changes from my repo to hopefully fix this until we can get the auth repo updated? It is only script changes so it wouldn't need to rebuild.

@WalterKolczynski-NOAA I see you poked Jiayi in the relevant TC_tracker issue. Will see if he responds. I can work with him to get that finished. I'll need tracker working for my work on issue #235 anyway.

**Comment by KateFriedman-NOAA** [comment] 2023-10-23 18:51
So the genesis worked fine when I ran tests on WCOSS2 last week in cycled atmos-only mode. Perhaps something is off in forecast-only mode. @JessicaMeixner-NOAA do you need tracker/genesis output? If not, suggest turning those pieces off for now in your runs. In your EXPDIR config.vrfy:
```
export VRFYTRAK="NO"             # Hurricane track verification
export VRFYGENESIS="NO"          # Cyclone genesis verification
```

I'm hoping to begin working on extracting the tracker/genesis tasks from the vrfy job (issue #235 work) later this week so I can try it in forecast-only mode to see what's going on.

**Comment by JessicaMeixner-NOAA** [comment] 2023-10-24 12:30
@KateFriedman-NOAA we are assessing performance of hurricanes with the high resolution prototypes so this is output we need.

**Comment by KateFriedman-NOAA** [comment] 2023-10-24 13:10
@JessicaMeixner-NOAA Noted...I am going to run the same case as you on Dogwood with your clone and try to see what's going wrong. Stay tuned...

**Comment by JessicaMeixner-NOAA** [comment] 2023-10-24 13:13
Thanks @KateFriedman-NOAA !

**Comment by KateFriedman-NOAA** [comment] 2023-10-24 15:56
@JessicaMeixner-NOAA Found the problem. We still need to set `SENDCOM="YES"` for the tracker/genesis jobs. That variable was removed recently but we still need it in the tracker/genesis jobs so I am going to make a hotfix for now and reevaluate it while I work to pull those jobs out of the vrfy job.

For now, add the following to your `config.vrfy`:
```
export SENDCOM="YES"
```

...then rerun the failed vrfy job. Let me know if that works. Thanks!

**Comment by JessicaMeixner-NOAA** [comment] 2023-10-24 18:16
@KateFriedman-NOAA adding export SENDCOM="YES" got me past errors on WCOSS2 and the job completed successfully.  I also found the proudcuts did exist: 

/lfs/h2/emc/couple/noscrub/jessica.meixner/HR3/updatemods/s2swc48t01/COMROOT/s2swc48t01/gfs.20210323/12/products/atmos/cyclone> ls *
genesis_vital:
all.vitals.gfs.gfso.2021  genesis.vitals.gfs.gfso.2021  storms.gfso.atcf_gen.altg.2021032312  trak.gfso.atcfunix.altg.2021032312

tracks:
avnop.t12z.cyclone.trackatcfunix  avno.t12z.cyclone.trackatcfunix

**Comment by KateFriedman-NOAA** [comment] 2023-10-24 18:23
@JessicaMeixner-NOAA Thanks for confirming adding `export SENDCOM="YES"` worked and that you now have outputs. I got the same outputs in my test.

I'll submit the hotfix now to add `SENDCOM="YES"` back in. I'll close this issue with the hotfix PR.

**Closed as completed** 2023-10-24 18:48 UTC
Labels: bug
