### ISSUE TITLE
Ensemble archive step does not clean old directories

### ISSUE THREAD

**Issue by CatherineThomas-NOAA** [NOAA-EMC/global-workflow#1872] opened 2023-09-20 21:43 UTC
### What is wrong?

When cycling with global-workflow develop, the enkfgdas directories in the ROTDIR are not being automatically deleted during the earc step.  

When @azadeh-gh ran a recent ATM-only C384/C192 experiment, several days of ensemble data remained in the ROTDIR.  This was observed on Hera; it's unclear if this impacts other machines.  

The log file says the target directories are missing, even though they were present at runtime: (/scratch2/NCEPDEV/stmp3/Azadeh.Gholoubi/TestExperiment/ThompsonMP2/logs/2023040800/enkfgdasearc00.log)

```
+ exgdas_enkf_earc.sh[150]: echo 'No directory /scratch2/NCEPDEV/stmp3/Azadeh.Gholoubi/TestExperiment/ThompsonMP2/enkfgdas.20230402/00/mem001
/analysis/atmos to remove files from, skiping'
```

All of the directory names seem to have a line break after the member number, but I'm not sure if this is part of the issue or not.  Note that since these jobs ran, the enkfgdas directories were deleted by hand to free up some stmp space.  

### What should have happened?

When the earc step runs, it should automatically remove ensemble data older than a few cycles. 

### What machines are impacted?

Hera

### Steps to reproduce

Cycle global-workflow develop ATM-only for at least 5 cycles on Hera.

### Additional information

N/A

**Comment by HenryWinterbottom-NOAA** [comment] 2023-09-25 14:55
@CatherineThomas-NOAA Do you have a working example of this still on RDHPCS Hera's disk? I can try to debug if you do.

**Comment by HenryRWinterbottom** [comment] 2023-09-25 15:04
@CatherineThomas-NOAA I found a path for `/scratch2/NCEPDEV/stmp3/Azadeh.Gholoubi/TestExperiment/ThompsonMP2/enkfgdas.20230409/00/` containing ENKF directories.

Can you run the 5-cycle experiment you listed above, can be any resolution you'd like, and I can use that as a starting point to debug? If so, please just point me to the path. Thank you!

**Comment by CatherineThomas-NOAA** [comment] 2023-09-25 15:52
@HenryWinterbottom-NOAA 
I have a C96/C48 experiment on Hera that I ran for something else.  I'll run it another few cycles and send you the path once it gets far enough.

**Comment by HenryRWinterbottom** [comment] 2023-09-25 15:53
Fantastic! Thank you!

**Comment by CatherineThomas-NOAA** [comment] 2023-09-25 20:42
@HenryWinterbottom-NOAA 
Here's a ROTDIR for you to look through:
/scratch1/NCEPDEV/stmp4/Catherine.Thomas/ROTDIRS/gcycle_dev

For example, in log file logs/2021122206/enkfgdasearc00.log at Line 41773:
```
+ exgdas_enkf_earc.sh[149]: [[ ! -d /scratch1/NCEPDEV/stmp4/Catherine.Thomas/ROTDIRS/gcycle_dev/enkfgdas.20211221/06/mem001
/model_data/atmos/restart ]]
+ exgdas_enkf_earc.sh[150]: echo 'No directory /scratch1/NCEPDEV/stmp4/Catherine.Thomas/ROTDIRS/gcycle_dev/enkfgdas.20211221/06/mem001
/model_data/atmos/restart to remove files from, skiping'
```

If you `ls` that directory (without the line break), it exists:
```
1054 hfe11% ls /scratch1/NCEPDEV/stmp4/Catherine.Thomas/ROTDIRS/gcycle_dev/enkfgdas.20211221/06/mem001//model_data/atmos/restart
20211221.030000.sfcanl_data.tile1.nc
20211221.030000.sfcanl_data.tile2.nc
...
```

Let me know if you need me to run any additional cycles.

**Comment by HenryRWinterbottom** [comment] 2023-09-25 21:39
Ok, thank you! Let me see what I can find.

**Comment by HenryRWinterbottom** [comment] 2023-09-26 19:47
@CatherineThomas-NOAA Can you please try my branch `bug/gdas_enkf_scrubbing` from my [fork](https://github.com/HenryWinterbottom-NOAA/global-workflow/) and let me know if the patch resolves your issue?

**Comment by CatherineThomas-NOAA** [comment] 2023-09-26 20:26
@HenryWinterbottom-NOAA 
Will do.  I'll report back once it gets far enough.

**Comment by CatherineThomas-NOAA** [comment] 2023-09-27 15:47
@HenryWinterbottom-NOAA 
My experiment has run long enough.  Your fix doesn't seem to be enough; the files are still there:
/scratch1/NCEPDEV/stmp4/Catherine.Thomas/ROTDIRS/earc

Something peculiar is happening.  In the logfile for 2021122212, it's attempting to remove the files and doesn't error:
```
+ exgdas_enkf_earc.sh[172]: for file in '"${file_list[@]}"'
+ exgdas_enkf_earc.sh[173]: rm -f '/scratch1/NCEPDEV/stmp4/Catherine.Thomas/ROTDIRS/earc/enkfgdas.20211220/18/mem001/model_data/atmos/restart/20211221.030000.phy_data.tile1.nc
'
+ exgdas_enkf_earc.sh[172]: for file in '"${file_list[@]}"'
+ exgdas_enkf_earc.sh[173]: rm -f '/scratch1/NCEPDEV/stmp4/Catherine.Thomas/ROTDIRS/earc/enkfgdas.20211220/18/mem001/model_data/atmos/restart/20211221.000000.sfc_data.tile6.nc
'
```

But the files still exist:
```
1054 hfe01% ls /scratch1/NCEPDEV/stmp4/Catherine.Thomas/ROTDIRS/earc/enkfgdas.20211220/18/mem001/model_data/atmos/restart/20211221.030000.phy_data.tile1.nc
/scratch1/NCEPDEV/stmp4/Catherine.Thomas/ROTDIRS/earc/enkfgdas.20211220/18/mem001/model_data/atmos/restart/20211221.030000.phy_data.tile1.nc
```

**Comment by HenryRWinterbottom** [comment] 2023-09-27 19:47
@CatherineThomas-NOAA Can you please update your branch such that it syncs with my updates and please try again?

**Comment by CatherineThomas-NOAA** [comment] 2023-09-28 13:03
@HenryWinterbottom-NOAA 
My ensemble directories have now been (mostly) cleared out.  Only the ensemble mean/spread remain, which I believe is intentional.  You can look at the relevant log here:
/scratch1/NCEPDEV/stmp4/Catherine.Thomas/ROTDIRS/earc/logs/2021122218/enkfgdasearc00.log

and a much cleaner directory here:
/scratch1/NCEPDEV/stmp4/Catherine.Thomas/ROTDIRS/earc/enkfgdas.20211221/00

This log is much longer than the previous earc logs as well, since it had to go back several cycles for cleaning.

One other concern of mine is whether this affects the deterministic side as well.  The removal time for gdasarch is longer than the ensemble so I haven't run long enough to try it out.  Should your changes be replicated for the gdasarch step as well?

**Comment by HenryRWinterbottom** [comment] 2023-09-28 13:52
Thank you @CatherineThomas-NOAA.

It appears as though it has worked. Can you please run a clean experiment for multiple DA cycles such that you might catch anything that I may have missed? If all appears well I can open a PR and close this.

**Comment by CatherineThomas-NOAA** [comment] 2023-10-02 18:50
@HenryWinterbottom-NOAA 
Unfortunately, the earc step failed with this error:
```
/scratch1/NCEPDEV/da/Catherine.Thomas/git/global-workflow/earc/scripts/exgdas_enkf_earc.sh: line 179: file_list[@]: unbound variable
```

You can find a full logfile here:
/scratch1/NCEPDEV/stmp4/Catherine.Thomas/ROTDIRS/earc/logs/2021122212/enkfgdasearc00.log.0

**Comment by HenryRWinterbottom** [comment] 2023-10-02 19:07
@CatherineThomas-NOAA I just updated my branch to try to catch that exception.

Can you please update your fork and try again? You can probably run that single job to test.

**Comment by CatherineThomas-NOAA** [comment] 2023-10-02 19:23
@HenryWinterbottom-NOAA 
Thanks for the update.  I incorporated the change and reran the latest earc job.  Same error except the log is listing a different line number:
```
/scratch1/NCEPDEV/da/Catherine.Thomas/git/global-workflow/earc/scripts/exgdas_enkf_earc.sh: line 208: file_list[@]: unbound variable
```
/scratch1/NCEPDEV/stmp4/Catherine.Thomas/ROTDIRS/earc/logs/2021122212/enkfgdasearc00.log

**Comment by HenryRWinterbottom** [comment] 2023-10-02 19:55
@CatherineThomas-NOAA Thank your trying.

I updated my branch and added an exception catch about the problematic `if` block.

Can you please try again and send me the result?

Thanks.

**Comment by CatherineThomas-NOAA** [comment] 2023-10-02 20:02
@HenryWinterbottom-NOAA 
```
/scratch1/NCEPDEV/da/Catherine.Thomas/git/global-workflow/earc/scripts/exgdas_enkf_earc.sh: line 343: unexpected EOF while looking for matching `"'
```

**Comment by HenryRWinterbottom** [comment] 2023-10-02 20:06
@CatherineThomas-NOAA Sorry, a typo on my end.

Can you please try again?

**Comment by CatherineThomas-NOAA** [comment] 2023-10-02 20:14
@HenryWinterbottom-NOAA 
And we've come full circle, but not in a good way:
```
/scratch1/NCEPDEV/da/Catherine.Thomas/git/global-workflow/earc/scripts/exgdas_enkf_earc.sh: line 212: file_list[@]: unbound variable
```

**Comment by HenryRWinterbottom** [comment] 2023-10-02 20:15
@CatherineThomas-NOAA Let me try to debug this locally rather than sending you single fixes.

I will leave this issue open by need find the root more efficiently.

Thank you for your patience.

**Comment by HenryRWinterbottom** [comment] 2023-10-03 17:54
@CatherineThomas-NOAA I rewrote the `remove_files` function. I created a local path that mocked your GDAS ENKF experiment. 

I realize that RDHPCS Hera is down for maintenance today, 03 October 2023. However, once access is available please update your branch and try again.

Thank you for your patience.

**Comment by HenryRWinterbottom** [comment] 2023-10-04 01:40
@CatherineThomas-NOAA please hold off on testing. I just realized a possible bug that I may have introduced. I will take a look in the morning. 

Stay tuned.

**Comment by HenryRWinterbottom** [comment] 2023-10-04 14:02
@CatherineThomas-NOAA I checked this morning and the branch seems ready for another test. There is another PR open #1906. If the solution that I am proposing does not work it might be worth considering what is being addressed in that PR.

**Comment by CatherineThomas-NOAA** [comment] 2023-10-04 14:23
@HenryWinterbottom-NOAA 
I gave it another try and unfortunately still had a failure:
```
+ exgdas_enkf_earc.sh[219]: remove_list=()
/scratch1/NCEPDEV/da/Catherine.Thomas/git/global-workflow/earc/scripts/exgdas_enkf_earc.sh: line 220: exclude_list: unbound variable
```

That PR looks like a good venue for a solution.  Anything here would need to be incorporated there anyway.

**Comment by HenryRWinterbottom** [comment] 2023-10-04 14:26
@CatherineThomas-NOAA please hold off on testing. I just realized a possible bug that I may have introduced. I will take a look in the morning. 

Stay tuned. 

Ok, we are closer. Let me dig some more since you have a test in place.

**Comment by HenryRWinterbottom** [comment] 2023-10-04 20:47
@CatherineThomas-NOAA I have been unable to reproduce your result so I am not sure if something in the runtime environment is different or what.

However, I did build a regression test for the remove_files function and tried to catch any edge-cases (perhaps yours is one).

Can you please update your branch and try again? If this does not solve the problem we may have to see what PR https://github.com/NOAA-EMC/global-workflow/pull/1906 yields.

Thank you for your patience.

**Comment by CatherineThomas-NOAA** [comment] 2023-10-04 21:42
@HenryWinterbottom-NOAA 
Not sure if I have something weird on my end, but I got another failure:
```
/scratch1/NCEPDEV/da/Catherine.Thomas/git/global-workflow/earc/scripts/exgdas_enkf_earc.sh: line 310: exclude_list[@]: unbound variable
++ exgdas_enkf_earc.sh[1]: postamble exgdas_enkf_earc.sh 1696452265 1
```

Once upon a time, there was some exception in the workflow where the archive steps would not flag a failure in the first few cycles, even if there was an error.  That's not what's going on here, is it?  If not, I'm good with letting that other PR play out and see how the testing goes over there.

**Comment by HenryRWinterbottom** [comment] 2023-10-04 21:48
@CatherineThomas-NOAA There is an exception being raised because the script sees `exclude_list` as empty even though it is defined. There must be a `bash` flag that is being set that causes this to fail. The `remove_files` replacement for the atmosphere seems to work. Is that correct?

@WalterKolczynski-NOAA Are you aware of any such bash setting that I should be aware of? The only one that I saw was `+x` in the `preamble.sh`.

**Comment by CatherineThomas-NOAA** [comment] 2023-10-05 19:17
@HenryWinterbottom-NOAA 
It seems to be the "set -u" that is run as part of [ush/preamble.sh:](https://github.com/NOAA-EMC/global-workflow/blob/2d64b74a0b0407d01d6f657efa6af9637a131448/ush/preamble.sh#L40)
```
set_strict() {
    if [[ ${STRICT:-"YES"} == "YES" ]]; then
        # Exit on error and undefined variable
        set -eu
    fi
}
```

When I include "set +u" just before the remove_files call, it passes through no problem.  I'm not sure if there are other consequences of setting it this way though.  Maybe @WalterKolczynski-NOAA can chime in.

**Comment by HenryRWinterbottom** [comment] 2023-10-05 19:20
@CatherineThomas-NOAA By "passes through fine" do you mean that it successfully removes the paths/files that you expect?

**Comment by WalterKolczynski-NOAA** [comment] 2023-10-05 19:23
Turning that off is only covering the problem up (the script no longer exits on an undefined variable), not fixing it.

**Comment by HenryRWinterbottom** [comment] 2023-10-05 19:25
@WalterKolczynski-NOAA @CatherineThomas-NOAA At this point I want to see what PR #1906 yields. If that is still broken I will open a new issue and try again. I will keep this open, however, until PR #1906 is merged.

**Comment by CatherineThomas-NOAA** [comment] 2023-10-05 19:35
@HenryWinterbottom-NOAA I meant that it got past that line in the script, but it failed elsewhere due to the same type of issue (I only turned it off locally then turned it back on) so I can't fully evaluate if it would have deleted things properly.

I'm curious though, shouldn't some of those variables be allowed to be empty?  It's defining an exclusion list for file deletions, so many times we would want it to be empty, wouldn't we?

**Comment by HenryRWinterbottom** [comment] 2023-10-05 19:37
@CatherineThomas-NOAA Yes, they should be empty. And, my unit-tests passed.

I am assuming that the global-workflow environment is prohibiting any instances based on the run-time environment. I haven't been able to chase down (yet) what exactly is the issue however.

**Comment by WalterKolczynski-NOAA** [comment] 2023-10-05 19:39
They can be undefined, but the function needs to be able to handle that and not try to use an undefined value.

**Closed as completed** 2023-10-20 15:54 UTC
Labels: bug, triage
