### ISSUE TITLE
Enable different coupled options (NSST on/off) and output frequencies in coupled models

### ISSUE THREAD

**Issue by JoshuaFu-NOAA** [NOAA-EMC/global-workflow#196] opened 2020-11-25 19:29 UTC

**Comment by JessicaMeixner-NOAA** [comment] 2021-02-03 13:37
@jiandewang isn't this already there in the feature/coupled-crow branch?

**Comment by jiandewang** [comment] 2021-02-03 14:57
@JessicaMeixner-NOAA no

**Comment by JoshuaFu-NOAA** [comment] 2021-02-03 23:57
c 

> 
> 
> @JessicaMeixner-NOAA no



> 
> 
> @jiandewang isn't this already there in the feature/coupled-crow branch?

better to make three flexible output frequency options, respectively, for atmosphere, ocean and ice components,  which can be modified from case yaml files?

**Comment by JoshuaFu-NOAA** [comment] 2021-02-03 23:58
need to add three one-stop control parameters.

**Comment by KateFriedman-NOAA** [comment] 2021-02-23 15:29
Please update issue, thanks!

**Comment by WalterKolczynski-NOAA** [comment] 2021-02-23 22:53
Closed as duplicate of #230

**Closed as completed by WalterKolczynski-NOAA** 2021-02-23 22:53 UTC
Labels: duplicate
