### ISSUE TITLE
Port aerosol cycling from coupled-crow for P8 development and tuning

### ISSUE THREAD

**Issue by rmontuoro** [NOAA-EMC/global-workflow#655] opened 2022-02-16 22:21 UTC
**Description**

The ability to cycle atmospheric tracers (aerosols), available in the coupled-crow version of global-workflow and used to develop and tune UFS-Aerosols for P7, needs to be ported to the current global-aerosol version for further UFS-Aerosols development targeted to P8c.

**Comment by WalterKolczynski-NOAA** [comment] 2022-02-16 22:27
Duplicate of #516

**Closed as completed** 2022-02-16 22:27 UTC
Labels: duplicate
