### ISSUE TITLE
Archiving fails in S2S trying to save sfluxgrb forecast files that are not created

### ISSUE THREAD

**Issue by AndrewEichmann-NOAA** [NOAA-EMC/global-workflow#1418] opened 2023-03-23 14:30 UTC
**Expected behavior**

Archiving task completes successfully

**Current behavior**

When running S2S, archiving fails on trying to archive sfluxgrb forecast files on "off-hours" (not divisible by 3), as these are currently not created. 

**Machines affected**

Hera

**To Reproduce**

Can be seen in `/scratch1/NCEPDEV/stmp4/Andrew.Eichmann/COMROT/ocn-da-lores/logs/2021032412/gdasarch.log.1 `starting on line 1001:

```
ERROR: /apps/hpss/bin/htar: error -1 stat-ing "./gdas.20210324/12/atmos/gdas.t12z.sfluxgrbf001.grib2"
*** Warning: No matching names located for './gdas.20210324/12/atmos/gdas.t12z.sfluxgrbf001.grib2'
ERROR: /apps/hpss/bin/htar: error -1 stat-ing "./gdas.20210324/12/atmos/gdas.t12z.sfluxgrbf001.grib2.idx"
*** Warning: No matching names located for './gdas.20210324/12/atmos/gdas.t12z.sfluxgrbf001.grib2.idx'
ERROR: /apps/hpss/bin/htar: error -1 stat-ing "./gdas.20210324/12/atmos/gdas.t12z.sfluxgrbf002.grib2"
*** Warning: No matching names located for './gdas.20210324/12/atmos/gdas.t12z.sfluxgrbf002.grib2'
ERROR: /apps/hpss/bin/htar: error -1 stat-ing "./gdas.20210324/12/atmos/gdas.t12z.sfluxgrbf002.grib2.idx"
*** Warning: No matching names located for './gdas.20210324/12/atmos/gdas.t12z.sfluxgrbf002.grib2.idx'
ERROR: /apps/hpss/bin/htar: error -1 stat-ing "./gdas.20210324/12/atmos/gdas.t12z.sfluxgrbf004.grib2"
*** Warning: No matching names located for './gdas.20210324/12/atmos/gdas.t12z.sfluxgrbf004.grib2'
ERROR: /apps/hpss/bin/htar: error -1 stat-ing "./gdas.20210324/12/atmos/gdas.t12z.sfluxgrbf004.grib2.idx"
*** Warning: No matching names located for './gdas.20210324/12/atmos/gdas.t12z.sfluxgrbf004.grib2.idx'
```

EXPDIR in `/scratch1/NCEPDEV/da/Andrew.Eichmann/WCDA/ocn-da-lores/ocn-da-lores/ocn-da-lores` (no typo)

**Context**
see below
**Detailed Description**
see below
**Additional Information**
see below

**Possible Implementation**

This is easily remedied incorrectly by commenting out on a local build, or semi-correctly with an if-then cutout for S2S for the following code, but I wonder if these files should be selected more dynamically from variables set in config files.

https://github.com/NOAA-EMC/global-workflow/blob/4ff622a36e3f9aa2f39e847a7b9e2b536ebcdc0a/ush/hpssarch_gen.sh#L344-L348

**Comment by WalterKolczynski-NOAA** [comment] 2023-08-14 05:27
I'm unable to reproduce this. [hpssarch_gen.sh](https://github.com/NOAA-EMC/global-workflow/blob/4ff622a36e3f9aa2f39e847a7b9e2b536ebcdc0a/ush/hpssarch_gen.sh#L344-L348) has changed quite a bit in the interim, is it possible this has already been fixed without this issue being updated?

**Comment by WalterKolczynski-NOAA** [comment] 2023-08-14 05:28
Looks like this was fixed some time ago and the issue was never closed. Please reopen if this is still a problem.

**Closed as completed by WalterKolczynski-NOAA** 2023-08-14 05:28 UTC
Labels: bug

**Comment by AndrewEichmann-NOAA** [comment] 2023-08-14 13:20
@WalterKolczynski-NOAA Thanks, and sorry
