### ISSUE TITLE
feature/coupled-crow installation broken on stampede2

### ISSUE THREAD

**Issue by benjamin-cash** [NOAA-EMC/global-workflow#308] opened 2021-03-26 14:07 UTC
The installation of the workflow on stampede2 breaks because it is pointing to an installation of hpc-stack that does not have general read permissions (chronic problem on stampede2). The problem is in this line:

module use -a /work/06146/tg854455/stampede2/ufs-stack-20200909/intel-18.0.2/impi-18.0.2/modules 

login1.stampede2(1047)$ ls -l /work/06146/tg854455/stampede2/ufs-stack-20200909/intel-18.0.2/impi-18.0.2/modules 
ls: cannot access /work/06146/tg854455/stampede2/ufs-stack-20200909/intel-18.0.2/impi-18.0.2/modules: Permission denied

It also looks like that might be an older version of hpc-stack?

**Comment by MinsukJi-NOAA** [comment] 2021-03-26 14:11
It is an older version. The ufs-weather-model is using a new one installed by @Hang-Lei-NOAA : https://github.com/ufs-community/ufs-weather-model/blob/37f0da7b82e32a15bf072eaa158399a6b0f2722c/modulefiles/stampede.intel/fv3#L17

**Comment by arunchawla-NOAA** [comment] 2021-03-26 14:11
@WalterKolczynski-NOAA and @JianKuang-NOAA we should be using the hpc-stack that was installed by @Hang-Lei-NOAA for the ufs-weather-model. I think the permissions there are correct as it was used by Ben to build the model without problems

**Comment by benjamin-cash** [comment] 2021-03-26 14:18
I definitely have a version of hpc-stack that I can see here: /work/08048/hanglei/NCEP/install/hpc-stack/modulefiles/stack. And it looks like machine-setup.sh is referring to that for stampede2. So I'm not sure now where that version of hpc-stack is coming in from.

**Comment by MinsukJi-NOAA** [comment] 2021-03-26 14:24
The stampede2 related changes were merged into the ufs-weather-model develop branch on 03/24. So, if the global workflow is pulling in a version that is older, that could be the reason.

**Comment by benjamin-cash** [comment] 2021-03-26 14:37
Stealing the stampede.intel/fv3 file from my ufs-weather-model install seems to be working, but I will pause there until the question of whether I have the right model version is resolved.

**Comment by JessicaMeixner-NOAA** [comment] 2021-03-26 14:39
When @WalterKolczynski-NOAA pulled in the last PR https://github.com/NOAA-EMC/global-workflow/pull/261 from @JianKuang-NOAA to the feature/coupled-crow branch, it was noted that the ufs-weather-model needed to be updated to the hash @MinsukJi-NOAA mentioned, and the hpc-stack version others have mentioned in this thread.  @WalterKolczynski-NOAA felt like it would be easier to make those changes via a separate PR, so #261 was merged and the updates to the modules and weather-model hash are ongoing.   I think he's working on that - I remember seeing a comment about post not building yesterday.

**Comment by benjamin-cash** [comment] 2021-03-26 14:45
Ok, I will hold until the rest of the updates go in.

**Comment by benjamin-cash** [comment] 2021-03-26 15:05
In case it is useful - build_ufs_coupled completed when I used the newer fv3 file, but build_reg2grb2 failed looking for libjasper.a and ncep_post failed with a variety of errors.

**Comment by WalterKolczynski-NOAA** [comment] 2021-03-26 17:58
As Jessica mentioned, the branch is not ready for use on Stampede yet. I'm working on cleaning it up and testing now. I will announce on the original porting issue when it is ready. Please sit tight until then.

Closing as duplicate of #280.

**Closed as completed by WalterKolczynski-NOAA** 2021-03-26 17:58 UTC
Labels: duplicate
