### ISSUE TITLE
setting up coupled workflow on Xsede platforms

### ISSUE THREAD

**Issue by arunchawla-NOAA** [NOAA-EMC/global-workflow#280] opened 2021-03-01 18:21 UTC
Once the coupled workflow is working using hpc-stack, we should do a migration of the workflow on XSEDE platforms. 

We can use stampede2 as a test case. The model and hpc-stack should already be available on the different XSEDE platforms

**Comment by Hang-Lei-NOAA** [comment] 2021-03-02 03:41
According to Arun's order:

I have modified hpc-stack to get used to the stampede2 machine compilers.
And installed the hpc-stack release v1.1.0 on stampede2.
(BTW, unlike comet,  the stampede2 need to be supported by university
account, my account was supported byTACC university fund)
To use it:

module use /work/08048/hanglei/NCEP/install/hpc-stack/modulefiles/stack
module load hpc/1.1.0
module load hpc-intel/18.0.2
module load hpc-impi/18.0.2

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
---------------------------------------------------------------
/work/08048/hanglei/NCEP/install/hpc-stack/modulefiles/mpi/intel/18.0.2/impi/18.0.2
----------------------------------------------------------------
   atlas/jcsda-release-stable    esmf/8_1_0_beta_snapshot_27    hdf5/1.10.6
  (D)    nceppost/dceca26    nemsio/2.5.2       netcdf/4.7.4 (D)
 upp/10.0.0     wgrib2/2.0.8
   eckit/jcsda-release-stable    fckit/jcsda-release-stable     nccmp/
1.8.7.0        ncio/1.0.0          nemsiogfs/2.5.3    pio/2.5.2
w3emc/2.7.3    wrf_io/1.1.1
-----------------------------------------------------------------
/work/08048/hanglei/NCEP/install/hpc-stack/modulefiles/compiler/intel/18.0.2
--------------------------------------------------------------------
   bacio/2.4.1    crtm/2.3.0    g2c/1.6.2       gfsio/1.4.1
 hpc-impi/18.0.2 (L)    ip2/1.1.2        jpeg/9.1.0           png/1.6.35
      sfcio/1.4.1    sp/2.3.3      udunits/2.2.28 (D)    zlib/1.2.11
   bufr/11.4.0    g2/3.4.1      g2tmpl/1.9.1    grib_util/1.2.2    ip/3.3.3
              jasper/2.0.25    landsfcutil/2.4.1    prod_util/1.2.2
 sigio/2.3.2    szip/2.1.1    w3nco/2.4.1
---------------------------------------------------------------------------
/work/08048/hanglei/NCEP/install/hpc-stack/modulefiles/core
----------------------------------------------------------------------------
   boost-headers/1.68.0    ecbuild/jcsda-release-stable    eigen/3.3.7 (D)
   hpc-intel/18.0.2 (L)    json-schema-validator/2.1.0    json/3.9.1
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

**Comment by Hang-Lei-NOAA** [comment] 2021-03-02 03:50
For the work on comet:
Since there is no lmod, and compiler is not standard installation, I have modified the hpc-stack to installed NCEP libraries there under a flat structure.  Minsuk Ji has helped a lot on testing my installations. We now have a working version there.

**Comment by WalterKolczynski-NOAA** [comment] 2021-03-02 14:21
@JianKuang-NOAA already has a PR for this (#261), but there have been no updates in a couple weeks.

**Comment by MinsukJi-NOAA** [comment] 2021-03-02 14:35
Back in September, I ported the old S2S model (before merged into the UFS-weather-model) to Stampede2 based on Kyle Gerheiser's hpc-stack installation there. I will port the UFS-weather-model to Stampede2 based on Hang's hpc-stack installation. I use the regression test framework to build and run a test.

Hang, my understanding is that XSEDE will use Expanse [(AMD machine)](https://www.sdsc.edu/services/hpc/hpc_systems.html) on SDSC, instead of Comet.

**Comment by Hang-Lei-NOAA** [comment] 2021-03-02 14:46
Thanks for letting me know the expanse machine will be used. We will
install NCEP libraries on any machine based on the project request.

**Comment by WalterKolczynski-NOAA** [comment] 2021-03-02 14:53
Based on the email from Christine, we have allocation on stampede2, expanse, and bridges-2

**Comment by MinsukJi-NOAA** [comment] 2021-03-17 18:48
@Hang-Lei-NOAA Do you know if hpc-stack libraries are installed on bridges2?
https://www.psc.edu/resources/bridges-2/user-guide-2/

**Comment by Hang-Lei-NOAA** [comment] 2021-03-17 18:57
Hi, Minsuk
It is not yet. I was trying once last month, but there are some issues due
to the inappropriate installation of the impi compiler in that system. You
can check that. They did not follow the intel instruction to install the
mpi compiler, but mixed the mpi with the serial intel compiler. That caused
a series of trouble when loading both. I either need time to modify the
hpc-stack to use the local compiler or reinstall a new intel mpi compiler.
After that try, I was working with NCO to solve the WCOSS 2 issues. I will
come back to bridges2 soon.

**Comment by WalterKolczynski-NOAA** [comment] 2021-03-25 20:30
@JianKuang-NOAA are you sure post built when you ported to Stampede, because it is not for me.

**Comment by jkuang-exploro** [comment] 2021-03-25 20:42
@WalterKolczynski-NOAA No. the UPP version in this PR only accomplish hpc-stack capability and built with cmake. I don’t think there’s a version of UPP working on stampede yet at the time I last test this PR. Probably other teams are working on it.

**Comment by arunchawla-NOAA** [comment] 2021-03-25 20:53
aren't we using inline post? hpc-stack should contain the UPP library

**Comment by WalterKolczynski-NOAA** [comment] 2021-03-25 20:55
We are. I'm not sure we need to build post on our own anymore. But right now the branch still is. I'm going to try without.

**Comment by WalterKolczynski-NOAA** [comment] 2021-03-26 01:39
@JianKuang-NOAA what about rocoto? I don't see a module for it anywhere.

**Comment by jiandewang** [comment] 2021-03-26 03:08
@WalterKolczynski-NOAA I guess you mean for @JianKuang-NOAA

**Comment by WalterKolczynski-NOAA** [comment] 2021-03-26 03:10
Oops. Sorry Jiande.

**Comment by WalterKolczynski-NOAA** [comment] 2021-03-30 14:18
@JianKuang-NOAA What did you do for rocoto on Stampede?

**Comment by WalterKolczynski-NOAA** [comment] 2022-08-31 07:35
Xsede has been commissioned, so I'm closing this issue.

**Closed as completed by WalterKolczynski-NOAA** 2022-08-31 07:35 UTC
Labels: port

**Comment by benjamin-cash** [comment] 2022-09-07 17:15
I'm fine with closing the ticket, but just for the sake of clarity XSEDE was just the organization that oversaw the allocation process and administration of the machines. The actual platforms (Stampede2, Frontera, Expanse, etc) are still very much in operation, just under a new organization (ACCESS). They will still be a high priority target for community use of UFS.
