### ISSUE TITLE
Need to update ufs_model to hash#281b32f or newer 

### ISSUE THREAD

**Issue by guoqing-noaa** [NOAA-EMC/global-workflow#2630] opened 2024-05-27 00:05 UTC
### What is wrong?

Hera and Jet need a newer ufs_model to run C768 experiments.

Otherwise, the model will crash and we will get a "`Fatal error in PMPI_Type_contiguous: Invalid count, error stack`" error.

### What should have happened?

Be able to run C768 forecasts on Hera or Jet

### What machines are impacted?

Hera, Jet

### Steps to reproduce

Run any C768 forecast-only experiment

### Additional information

The problem was reported at
https://github.com/ufs-community/ufs-weather-model/issues/2227
and was fixed by this PR: 
https://github.com/ufs-community/ufs-weather-model/pull/2201

### Do you have a proposed solution?

Update ufs_model to hash#281b32f or newer 

If there are no current PRs to update this, I can create a new PR for this purpose. Thanks!

**Comment by WalterKolczynski-NOAA** [comment] 2024-05-28 15:11
Duplicate of #2490

**Closed as not planned by WalterKolczynski-NOAA** 2024-05-28 15:11 UTC
Labels: bug, triage
