### ISSUE TITLE
Checkout and build_all do not report errors

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#928] opened 2022-07-22 19:16 UTC
**Expected behavior**
Errors during the checkout or build process should be reported to STDOUT.

**Current behavior**
Errors are silent unless you read the logs.

**Machines affected**
All

**To Reproduce**
Edit checkout.sh to checkout one of the components from some non-existent repo or one you don't have access to.

**Context**
The error codes from the checkouts are being swallowed by the redirection of the output to the log file.

**Detailed Description**
Output from the `git clone` or component build script is being redirected to a log file. This obscures the error code of the command in checkout.sh and build_all.sh, so even though they are checking the return code, it is always 0.

**Additional Information**

**Possible Implementation**

**Comment by KateFriedman-NOAA** [comment] 2023-02-01 20:00
Attempt to reproduce the error described in this issue:

1. made a fresh clone of `develop`
2. changed a repo name in `checkout.sh` to be knowingly incorrect, removed the "u" from the gfs-utils repo name:
```
checkout "gfs_utils.fd"    "https://github.com/NOAA-EMC/gfs-tils"              "0b8ff56"                    ; errs=$((errs + $?))
```
3. ran `./checkout.sh -g`
4. confirmed WARNING message appears for failed checkout of "gfs-tils" (twice - first with clone attempt and again at end of checkout process):
```
-bash-4.2$ ./checkout.sh -g
Received -g flag for optional checkout of GSI-based DA
Performing checkout of gfs_utils
|-- Cloning from https://github.com/NOAA-EMC/gfs-tils into gfs_utils.fd
    WARNING: Error while cloning gfs_utils

Performing checkout of ufs_model
|-- Cloning from https://github.com/ufs-community/ufs-weather-model into ufs_model.fd
|-- Checking out 7a1ce44
|-- Updating submodules (if any)

Performing checkout of ufs_utils
|-- Cloning from https://github.com/ufs-community/UFS_UTILS.git into ufs_utils.fd
|-- Checking out 8b990c0
|-- Updating submodules (if any)

Performing checkout of verif-global
|-- Cloning from https://github.com/NOAA-EMC/EMC_verif-global.git into verif-global.fd
|-- Checking out c267780
|-- Updating submodules (if any)

Performing checkout of gsi_enkf
|-- Cloning from https://github.com/NOAA-EMC/GSI.git into gsi_enkf.fd
|-- Checking out 48d8676

Performing checkout of gsi_utils
|-- Cloning from https://github.com/NOAA-EMC/GSI-Utils.git into gsi_utils.fd
|-- Checking out 322cc7b
|-- Updating submodules (if any)

Performing checkout of gsi_monitor
|-- Cloning from https://github.com/NOAA-EMC/GSI-Monitor.git into gsi_monitor.fd
|-- Checking out c64cc47
|-- Updating submodules (if any)

Performing checkout of gldas
|-- Cloning from https://github.com/NOAA-EMC/GLDAS.git into gldas.fd
|-- Checking out fd8ba62
|-- Updating submodules (if any)

WARNING: One or more errors encountered during checkout process, please check logs before building
```
5. confirmed an error is still printed to checkout log for gfs-utils:
```
-bash-4.2$ cat logs/checkout_gfs_utils.log 
Cloning into 'gfs_utils.fd'...
remote: Repository not found.
fatal: repository 'https://github.com/NOAA-EMC/gfs-tils/' not found
```
6. tried to then run `build_all.sh` but it failed immediately since it needs `detect_machine.sh` and `module-setup.sh` from gfs-utils:
```
-bash-4.2$ ./build_all.sh 
Creating ../exec folder
./build_all.sh: line 77: gfs_utils.fd/ush/detect_machine.sh: No such file or directory
./build_all.sh: line 78: gfs_utils.fd/ush/module-setup.sh: No such file or directory
FATAL: Unable to determine target machine
```
7. revert change to gfs-utils checkout and reran `checkout.sh -g` to checkout gfs-utils
8. deleted Hera modulefile in `gfs-utils.fd` to force a build failure
9. ran `build_all.sh` and it spat out an error message about building gfs-utils:
```
-bash-4.2$ ./build_all.sh 
Resetting modules to system default. Reseting $MODULEPATH back to system default. All extra directories will be removed from $MODULEPATH.
 .... Building gfs_utils .... 
Fatal error in building gfs_utils.
The log file is in /scratch1/NCEPDEV/global/Kate.Friedman/git/develop_checkout_err_test/sorc/logs/build_gfs_utils.log
 .... Building WW3 pre and post execs .... 
```
10. the gfs-utils build log has the expected error message within:
```
-bash-4.2$ cat logs/build_gfs_utils.log 
++ pwd
+ cwd=/scratch1/NCEPDEV/global/Kate.Friedman/git/develop_checkout_err_test/sorc
+ OPTIND=1
+ getopts :dvh option
+ shift 0
+ BUILD_TYPE=Release
+ BUILD_VERBOSE=NO
+ /scratch1/NCEPDEV/global/Kate.Friedman/git/develop_checkout_err_test/sorc/gfs_utils.fd/ush/build.sh
Resetting modules to system default. Reseting $MODULEPATH back to system default. All extra directories will be removed from $MODULEPATH.
Lmod has detected the following error: The following module(s) are unknown: "gfsutils_hera.intel"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore_cache load "gfsutils_hera.intel"

Also make sure that all modulefiles written in TCL start with the string #%Module
```

**Comment by KateFriedman-NOAA** [comment] 2023-02-01 20:02
Unable to reproduce problem reported in this issue. If it did exist it was fixed somewhere along the way. Closing as "can't repo".

**Closed as not planned by KateFriedman-NOAA** 2023-02-01 20:02 UTC
Labels: bug
