### ISSUE TITLE
gdasefcs task failure with NaN inputs to mpp_reproducing_sum(_2d), representing numerical instability

### ISSUE THREAD

**Issue by BrettHoover-NOAA** [NOAA-EMC/global-workflow#856] opened 2022-06-14 16:37 UTC
**Description**
MEMBER 060 of the gdasefcs30 task is failing, with the log-file citing the following error:
1. A series of range violations from range_check, reporting out-of-bounds warnings
```
  0:  end of assign_importdata
  0:  PASS: fcstRUN phase 1, na =           72  time is    4.00236606597900     
  0:  Range_check Warning:DELP max =    1787.26760548720       min = 
  0:   -118.207090872696     
  0:  Range violation on: 2020/ 8/18 12: 7:30
  0: NOTE from PE     0: ==> Error from range_check: data out of bound
105: Warn_K= 127 (i,j)=   62   83 (lon,lat)=253.004  17.518 DELP =-118.20709
105:      K= 126    259.16316
  0:  Range_check Warning:Qv max =   2.402856749627384E-002  min = 
  0:  -6.910672349008115E-003
  0:  Range violation on: 2020/ 8/18 12: 7:30
  0: NOTE from PE     0: ==> Error from range_check: data out of bound
105: Warn_K= 127 (i,j)=   62   83 (lon,lat)=253.004  17.518 Qv =  -0.00691
105:      K= 126      0.02127
  0:  PASS: fcstRUN phase 2, na =           72  time is   0.289832830429077     
  0:  n fv3_cap,in model run, advance,na=          97
```
2. A series of "FATAL from PE" errors reporting NaN values representing a numerical instability, e.g.:
```
105: FATAL from PE   105: NaN in input field of mpp_reproducing_sum(_2d), this indicates numerical instability
```
3. Backtrace of failure, e.g.:
```
110: Image              PC                Routine            Line        Source             
110: ufs_model          0000000004ABB8FA  Unknown               Unknown  Unknown
110: ufs_model          00000000037F2EFC  mpp_mod_mp_mpp_er          71  mpp_util_mpi.inc
110: ufs_model          0000000003A94E3F  mpp_efp_mod_mp_mp         198  mpp_efp.F90
110: ufs_model          00000000039F2A09  mpp_domains_mod_m         137  mpp_global_sum.h
110: ufs_model          0000000002B7629F  fv_grid_utils_mod        3064  fv_grid_utils.F90
110: ufs_model          0000000002BAF9A7  fv_mapz_mod_mp_la         793  fv_mapz.F90
110: libiomp5.so        00002B614B391A43  __kmp_invoke_micr     Unknown  Unknown
110: libiomp5.so        00002B614B354CDA  Unknown               Unknown  Unknown
110: libiomp5.so        00002B614B3565B6  __kmp_fork_call       Unknown  Unknown
110: libiomp5.so        00002B614B314BB0  __kmpc_fork_call      Unknown  Unknown
110: ufs_model          0000000002BAAEB9  fv_mapz_mod_mp_la         682  fv_mapz.F90
110: ufs_model          0000000002B54705  fv_dynamics_mod_m         756  fv_dynamics.F90
110: ufs_model          0000000002ACF604  atmosphere_mod_mp         669  atmosphere.F90
110: ufs_model          0000000002A014CE  atmos_model_mod_m         763  atmos_model.F90
110: ufs_model          00000000028C6CBA  module_fcst_grid_         752  module_fcst_grid_comp.F90
110: ufs_model          00000000009D43CE  _ZN5ESMCI6FTable1        2167  ESMCI_FTable.C
110: ufs_model          00000000009D8386  ESMCI_FTableCallE         824  ESMCI_FTable.C
110: ufs_model          0000000000CDC68F  _ZN5ESMCI3VMK5ent        2273  ESMCI_VMKernel.C
110: ufs_model          00000000007976EA  _ZN5ESMCI2VM5ente        1216  ESMCI_VM.C
110: ufs_model          00000000009D5A67  c_esmc_ftablecall         981  ESMCI_FTable.C
110: ufs_model          0000000000831BC1  esmf_compmod_mp_e        1222  ESMF_Comp.F90
110: ufs_model          0000000000B941A4  esmf_gridcompmod_        1891  ESMF_GridComp.F90
110: ufs_model          00000000028BC80A  fv3gfs_cap_mod_mp        1063  fv3_cap.F90
110: ufs_model          00000000028BAA01  fv3gfs_cap_mod_mp         962  fv3_cap.F90
110: ufs_model          0000000000DDD77F  _ZNK5ESMCI13Metho         377  ESMCI_MethodTable.C
110: ufs_model          0000000000DDD702  _ZN5ESMCI11Method         563  ESMCI_MethodTable.C
110: ufs_model          0000000000DDBC06  c_esmc_methodtabl         317  ESMCI_MethodTable.C
110: ufs_model          00000000009C8700  esmf_attachmethod        1287  ESMF_AttachMethods.F90
110: ufs_model          0000000003111530  nuopc_modelbase_m        2220  NUOPC_ModelBase.F90
110: ufs_model          00000000009D43CE  _ZN5ESMCI6FTable1        2167  ESMCI_FTable.C
110: ufs_model          00000000009D8386  ESMCI_FTableCallE         824  ESMCI_FTable.C
110: ufs_model          0000000000CDC68F  _ZN5ESMCI3VMK5ent        2273  ESMCI_VMKernel.C
110: ufs_model          00000000007976EA  _ZN5ESMCI2VM5ente        1216  ESMCI_VM.C
110: ufs_model          00000000009D5A67  c_esmc_ftablecall         981  ESMCI_FTable.C
110: ufs_model          0000000000831BC1  esmf_compmod_mp_e        1222  ESMF_Comp.F90
110: ufs_model          0000000000B941A4  esmf_gridcompmod_        1891  ESMF_GridComp.F90
110: ufs_model          00000000007C00B9  nuopc_driver_mp_r        3332  NUOPC_Driver.F90
110: ufs_model          00000000007BF913  nuopc_driver_mp_e        3606  NUOPC_Driver.F90
110: ufs_model          0000000000DDD77F  _ZNK5ESMCI13Metho         377  ESMCI_MethodTable.C
110: ufs_model          0000000000DDD702  _ZN5ESMCI11Method         563  ESMCI_MethodTable.C
110: ufs_model          0000000000DDBC06  c_esmc_methodtabl         317  ESMCI_MethodTable.C
110: ufs_model          00000000009C8700  esmf_attachmethod        1287  ESMF_AttachMethods.F90
110: ufs_model          00000000007BC80D  nuopc_driver_mp_r        3253  NUOPC_Driver.F90
110: ufs_model          00000000009D43CE  _ZN5ESMCI6FTable1        2167  ESMCI_FTable.C
110: ufs_model          00000000009D8386  ESMCI_FTableCallE         824  ESMCI_FTable.C
110: ufs_model          0000000000CDC68F  _ZN5ESMCI3VMK5ent        2273  ESMCI_VMKernel.C
110: ufs_model          00000000007976EA  _ZN5ESMCI2VM5ente        1216  ESMCI_VM.C
```

Rewinding and rebooting the gdasefcs30 task does not appear to affect the outcome, with this error repeating on each reboot.

Expected behavior is for all gdasefcs30 members to successfully complete and continue cycling.

**Dependencies**
1. Searching through existing issues, it appears that this issue shares characteristics with the range_check issue on EFSOI forecast members cited in https://github.com/NOAA-EMC/global-workflow/issues/705. In that issue, there appear to be differing opinions about whether DELTIM should be reduced and whether it constitutes a fix to the problem. In issue #705 the user was asked to confirm if ```psm_bc=1``` in their namelist, and I can confirm I have ```psm_bc=1``` in my own namelist.
2. global-workflow is a copy of 96347ea527f7b0ab61a1aae6576e2709fb387c7c. 
3. The experiment we are running only assimilates conventional observations, and all satellite observations are set to monitoring in DA. I am curious if this kind of configuration may be more susceptible to the emergence of instabilities and require a reduction in DELTIM to address.
4. Another configuration choice that was made is that this experiment was initialized from a cold-start on Orion, and as a result has ```DO_GLDAS=NO``` set in config.fcst to avoid known issues with GLDAS from a cold-start detailed in https://github.com/NOAA-EMC/global-workflow/issues/622. I don't know if this might also make the configuration more susceptible to the emergence of instabilities.
5. This experiment was cold-start initialized on 2020073118, and this instability issue first surfaced on the 2020081806 cycle.

**Comment by WalterKolczynski-NOAA** [comment] 2022-06-14 17:02
I know cycling doesn't work in current develop, but the version of global workflow used here is a year old. The likely answer is that DELTIM needs to be reduced for whatever you're doing, but we can't chase bugs from year-old versions. Even then, if the need to increase DELTIM is due to other configuration changes, that's the responsibility of the user and not a bug.

Closing for now. If the result can be repeated with [pre_p8b](https://github.com/NOAA-EMC/global-workflow/releases/tag/pre_p8b), feel free to reopen.

**Closed as not planned by WalterKolczynski-NOAA** 2022-06-14 17:02 UTC
Labels: bug, wontfix

**Comment by BrettHoover-NOAA** [comment] 2022-06-14 17:09
Hi [WalterKolczynski-NOAA](https://github.com/WalterKolczynski-NOAA), I believe that this is a pre_p8b tag version of the code, but I don't know how to confirm that - my copy of the global-workflow is a direct copy of another user's code and they have told me this was a pre_p8b tag version. I hunted around their global-workflow's .git for the information on where it was cloned, but is there a way to confirm if my (their) global-workflow is pre_p8b?

**Comment by WalterKolczynski-NOAA** [comment] 2022-06-14 17:14
If you do a `git log`, it will give you the commit hash you are on and any tags or branches that point to it. But you're initial post said it used 96347ea, which was merged 2021 Jun 23. Tag pre_8b was created at the end of March this year.

**Comment by BrettHoover-NOAA** [comment] 2022-06-14 17:25
[WalterKolczynski-NOAA](https://github.com/WalterKolczynski-NOAA) I see the problem - I was looking at a global-workflow from the user in the wrong subdirectory, not the one I originally copied. I cannot find their git branch/tag information, which makes me think that their version was copied from yet another user.

I will try to track this down to confirm that the version we are using is pre_p8b and get back to you if that is the case, and in the mean time I will try to reduce DELTIM to 360 remove the instability problem. I appreciate your attention to this - thank you!
