### ISSUE TITLE
GFS v16.1.2.1:  TAC to BUFR for SHIPS, CMAN and Tide Gauge Stations

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/global-workflow#341] opened 2021-06-10 10:41 UTC
ObsProc has completed standalone testing of TAC to BUFR changes ships, cman, and tide gauge stations.   These changes need to be cycled in the global workflow before ObsProc submits the changes to NCO for implementation.   An experimental GDA directory needs to be created and populated with the new dump files.   Workflow changes are minimal - basically point at new ObsProc branches to process the new dump files.

This issue is opened to document this parallel testing and associated workflow changes.

- [x] install final OT tags everywhere
- [x] update HOMEobsproc variables in config.base in release/gfsv16.1.2.1 branch
- [x] update HOMEobsproc variables in config.base in develop

**Comment by KateFriedman-NOAA** [comment] 2021-06-10 14:32
Created release/gfsv16.1.3 branch for this work, cut from the current state of the release/gfsv16.1.2 branch (what is about to be ops).

**Comment by lgannoaa** [comment] 2021-06-20 23:29
Starting 2021062006 parallel v16tac2bfr has been moved to emc.gloparadev account. 

The following files were changed:
config.base and v16tac2bfr.xml
expdir: /gpfs/dell2/emc/modeling/noscrub/emc.gloparadev/para_fv3gfs/v16tac2bfr
HOMEgfs:/gpfs/dell2/emc/modeling/noscrub/emc.glopara/git/global-workflow/release_gfsv16.1.3
ROTDIR:/gpfs/dell3/ptmp/emc.gloparadev/ROTDIRS/v16tac2bfr/gfs/para
ARCDIR:/gpfs/dell2/emc/modeling/noscrub/emc.gloparadev/archive/v16tac2bfr

The cycle 2021062006 has been rerun to ensure it reproduce the source parallel.

**Comment by RussTreadon-NOAA** [comment] 2021-06-20 23:43
Given that the 2021062006 cycle has been rerun under emc.gloparadev, the emc.glopara v16tac2bfr EDATE has been changed to 2021062012.   The emc.glopara v16tac2bfr cron will be disabled upon completion of the 2021062012 cycle.

**Comment by RussTreadon-NOAA** [comment] 2021-06-21 09:14
The emc.glopara v16tac2bfr completed 2021062012.  The emc.glopara v16tac2bfr has been terminated and cron disabled.  Subsequent v16tac2bfr cycles will be run by emc.gloparadev.

**Comment by RussTreadon-NOAA** [comment] 2021-06-21 09:57
**b4b comparison**
Confirm emc.gloparadev 2021062012 v16tac2bfr b4b reproduced cycled files from emc.glopara 2021062012 v16tac2bfr.

**Comment by RussTreadon-NOAA** [comment] 2021-06-21 10:11
**Two Critical Reminders**

1. The v16tac2bfr `HOMEgfs` contains a locally modified `prep.sh` (see below) to pick up t2b dump files from GDAy.   

```
## TEST
## WARNING:  TEMPORARY PATCH
echo " "
echo "***WARNING***"
echo "***WARNING*** executing temporary patch in prep.sh"
echo "***WARNING*** start patch"
echo " "

ADPSFCBF=${CDUMP}.t${cyc}z.adpsfc.tm00.bufr_d
SFCSHPBF=${CDUMP}.t${cyc}z.sfcshp.tm00.bufr_d
TIDEGBF=${CDUMP}.t${cyc}z.tideg.tm00.bufr_d
ls -l $ROTDIR/$CDUMP.$PDY/$cyc/atmos/${ADPSFCBF}
ls -l $ROTDIR/$CDUMP.$PDY/$cyc/atmos/${SFCSHPBF}
##ls -l $ROTDIR/$CDUMP.$PDY/$cyc/atmos/${TIDEGBF}
rm $ROTDIR/$CDUMP.$PDY/$cyc/${ADPSFCBF}
rm $ROTDIR/$CDUMP.$PDY/$cyc/${SFCSHPBF}
##rm $ROTDIR/$CDUMP.$PDY/$cyc/${TIDEGBF}
ln -fs $DMPDIR/${CDUMP}y.$PDY/${cyc}/${ADPSFCBF} $ROTDIR/$CDUMP.$PDY/$cyc/atmos/${ADPSFCBF}
ln -fs $DMPDIR/${CDUMP}y.$PDY/${cyc}/${SFCSHPBF} $ROTDIR/$CDUMP.$PDY/$cyc/atmos/${SFCSHPBF}
ln -fs $DMPDIR/${CDUMP}y.$PDY/${cyc}/${TIDEGBF} $ROTDIR/$CDUMP.$PDY/$cyc/atmos/${TIDEGBF}

echo " "
echo "***WARNING*** end patch"
```

Please remember this if a fresh clone of [release/gfs.v16.1.3](https://github.com/NOAA-EMC/global-workflow/tree/release/gfsv16.1.3) is installed.  `prep.sh` will need to be manually modified before cycling with the fresh clone.   


2. The `v16tac2bfr.xml` has been manually modified to put GDAy dump file dependencies on the gfs and gdas prep steps.  For example, here are the gdas GDAy prep dependencies

```
         <datadep><cyclestr>&DMPDIR;/gdasy.@Y@m@d/@H/gdas.t@Hz.adpsfc.tm00.bufr_d</cyclestr></datadep>
         <datadep><cyclestr>&DMPDIR;/gdasy.@Y@m@d/@H/gdas.t@Hz.sfcshp.tm00.bufr_d</cyclestr></datadep>
         <datadep><cyclestr>&DMPDIR;/gdasy.@Y@m@d/@H/gdas.t@Hz.tideg.tm00.bufr_d</cyclestr></datadep>
```
We do not want the prep step to run without the GDAy dump files.   Please remember this if `setup_workflow.py` is executed to update `v16tac2bfr.xml` (e.g., to switch from phase 3.5 to phase 3 nodes).   Execution of `setup_workflow.py` will remove the manually added dependencies.   The gfs and gdas GDAy dependencies will need to be manually added to the updated `v16tac2bfr.xml`.

**Comment by KateFriedman-NOAA** [comment] 2021-06-23 14:11
Sync merged release/gfsv16.1.3 with operations branch at de5c90d78a3d116080dcfaf933ea50b7809cb3dc to fast-forward to HEAD of operations branch.

**Comment by KateFriedman-NOAA** [comment] 2021-07-20 13:12
OBSPROC release branches created and submitted to NCO, awaiting implementation and OT tags cut:

- obsproc_prep.v5.5.0
- obsproc_global.v3.4.2

Available via VLab:
git clone -b obsproc_prep_RB-5.5.0 https://user.name@vlab.noaa.gov/code-review/a/EMC_obsproc_prep obsproc_prep_RB-5.5.0
git clone -b obsproc_global_RB-3.4.2 https://User.Name@vlab.noaa.gov/code-review/a/EMC_obsproc_global obsproc_global_RB-3.4.2

**Comment by ShelleyMelchior-NOAA** [comment] 2021-07-20 14:40
One minor correction, the URLs in the clone instructions should no longer
contain ".ncep"

It might still work b/c I think redirection is still in place, but that may
not be the case forever.

Thanks,
Shelley

-- 
Shelley Melchior
IMSG - NOAA/NCEP/EMC - Obs Processing

**Comment by KateFriedman-NOAA** [comment] 2021-07-20 14:41
@ShelleyMelchior-NOAA Noted, make sure to update any gerrit aliases, the redirection does not work for gerrit. Thanks!

**Comment by RussTreadon-NOAA** [comment] 2021-07-20 15:46
**Venus prep test**

`obsproc_global_RB-3.4.2` and `obsproc_prep_RB-5.5.0` were installed on Venus.  The v16tac2bufr parallel configuration was used to run 2021072000 gfs and gdas prep twice.   The first run used `obsproc_global.iss83047.shipsb` and `obsproc_prep.iss83047.shipsb`.   The second run used `obsproc_global_RB-3.4.2` and `obsproc_prep_RB-5.5.0`.    

For this single cycle iss83047 and RB yield b4b identical output files apart from `where_t00z_${CDUMP}_prep_ran`.   Differences in `where_t00z_${CDUMP}_prep_ran` are expected and acceptable.   The b4b identical result for other files is expected.   

The v16tac2bfr parallel should be updated to `obsproc_global_RB-3.4.2` and `obsproc_prep_RB-5.5.0` since these were delivered to NCO for implementation.

**Comment by RussTreadon-NOAA** [comment] 2021-07-23 01:42
As requested, `obsproc_global_RB-3.4.2` and `obsproc_prep_RB-5.5.0` have been installed on Mars and Venus in `/gpfs/dell2/emc/modeling/noscrub/emc.glopara/git/obsproc/TAC2BUFR`.

**Comment by RussTreadon-NOAA** [comment] 2021-08-04 15:44
Click [here to view SCN](https://www.weather.gov/media/notification/pdf2/scn21-72_bufr_format_ships_c-man_data.pdf) posted for 20210810 implementation of gfs changes tested in v16tac2bfr.

**Comment by RussTreadon-NOAA** [comment] 2021-08-06 19:14
**NCO RFC memo - August 6, 2021**

***RFC 8521 - On WCOSS, implement obsprocv16. This upgrade primarily
addresses the ability to encode BUFR format ships and C-MAN platform data
into all obsproc-supported networks’ dump and prepbufr files. Networks include:
gdas, gfs, rap, rtma, urma, nam, cdas, and dump_monitor. For full details, see
the SCN at:
[https://www.weather.gov/media/notification/pdf2/scn21-72_bufr_format_ships_cman_
data.pdf](https://www.weather.gov/media/notification/pdf2/scn21-72_bufr_format_ships_c-man_data.pdf) . To be implemented on August 10 at 1135Z.

**Comment by KateFriedman-NOAA** [comment] 2021-08-10 16:27
CWD delayed upgrade on August 10th. New implementation date is August 16th.

**Comment by KateFriedman-NOAA** [comment] 2021-08-10 17:08
Renamed release/gfsv16.1.3 branch to release/gfsv16.1.2.1.

**Comment by RussTreadon-NOAA** [comment] 2021-08-11 10:24
**v16tac2bfr**

EIB moved v16tac2bfr from dev2 to dev in order to reach EDATE prior to 8/12 production switch.   Given 8/16 implementation date for ObsProc upgrade and the amount of effort to move v16tac2bfr from Venus to Mars following 8/12 production switch, recommend v16tac2bfr be terminated upon reaching EDATE=2021081012.   Ideally would keep v16tac2bfr running in real-time up to 8/12 switch but the v16tac2bfr fell too far behind real-time.   Other parallels need Venus clock cycles to reach good stopping point before 8/12 switch.   

v16tac2bfr [monitoring and verification page](https://www.emc.ncep.noaa.gov/gmb/emc.gloparadev/metplus/v16tac2bfr/) shows largely neutral impact.   One exception is SFCSHP fit2obs.   v16tac2bfr SFCSHP pressure fits show larger initial [bias](https://www.emc.ncep.noaa.gov/gmb/emc.gloparadev/metplus/v16tac2bfr/fit2obs/images/bias_SFCSHP_p_sfc_v16tac2bfr_all.png) and [rmse](https://www.emc.ncep.noaa.gov/gmb/emc.gloparadev/metplus/v16tac2bfr/fit2obs/images/rmse_SFCSHP_p_sfc_v16tac2bfr_all.png).   Click here for fnl [bias](https://www.emc.ncep.noaa.gov/gmb/emc.gloparadev/metplus/v16tac2bfr/fit2obs/images/bias_SFCSHP_p_sfc_fnl_all.png) and [rmse](https://www.emc.ncep.noaa.gov/gmb/emc.gloparadev/metplus/v16tac2bfr/fit2obs/images/rmse_SFCSHP_p_sfc_fnl_all.png).  v16tac2bfr assimilates a significantly larger number of SFCSHP observations than fnl (operations).    The overall v16tac2bfr -vs- fnl [scorecard](https://www.emc.ncep.noaa.gov/gmb/emc.glopara/vsdb/v16tac2bfr/www/scorecard/mainindex.html) shows acceptable performance.

**Comment by KateFriedman-NOAA** [comment] 2021-08-16 13:18
NCO RFC memo - August 13, 2021

RFC 8521 - On WCOSS, implement obsprocv16. This upgrade primarily addresses the ability to encode BUFR format ships and C-MAN platform data into all obsproc supported networks’ dump and prepbufr files. Networks include:
gdas, gfs, rap, rtma, urma, nam, cdas, dump_monitor. For full details, see the
SCN at: https://www.weather.gov/media/notification/pdf2/scn21-72_bufr_format_ships_c-man_data.pdf . 

Was to be implemented on August 10 at 1135Z; postponed due to CWD; new date is August 16 at 1135Z.

**Comment by KateFriedman-NOAA** [comment] 2021-08-16 13:25
Prep job issues over the weekend may impact this upgrade. See [SDM log from August 13th.](http://www2.nco.ncep.noaa.gov/pmb/sdmlogs/aug/13/) 
```
1i. 2016Z - EMC's Shelley and SPA Xiaoxue discussed how to go
forward. EMC plans to have an obsproc_prep_RB-5.5.0 release this
weekend, no later than Monday. Xiaoxue recommended they just
update the package to be implemented after CWD ends on 8/18.
(RRH)
```

Awaiting implementation and/or delay due to continued CWD.

**Comment by ShelleyMelchior-NOAA** [comment] 2021-08-16 14:53
Yes, obsproc_prep_RB-5.5.0 was revised on Saturday.  Revisions can be
pulled.  Xiaoxue indicates new implementation date is 8/18.

-- 
Shelley Melchior
IMSG - NOAA/NCEP/EMC - Obs Processing

**Comment by KateFriedman-NOAA** [comment] 2021-08-16 14:57
> Yes, obsproc_prep_RB-5.5.0 was revised on Saturday.  Revisions can be
pulled.  Xiaoxue indicates new implementation date is 8/18.

Thanks @ShelleyMelchior-NOAA ! I will update and rebuild relevant installs of the RB everywhere. I will install OT tags when available as well after implementation.

**Comment by KateFriedman-NOAA** [comment] 2021-08-16 15:32
The obsproc_prep_RB-5.5.0 installs on WCOSS-Dell (Mars and Venus), Hera, and Orion have been updated and rebuilt. I also rebuilt the hpc-stack modified versions on WCOSS-Dell, Hera, Orion, and Jet. Note: there is no non-stack version on Jet since we will not be including Jet support in the operations branch at this time.

The global-workflow config.base in operations branch will use symlinks in install directories to the RB versions:
* obsproc_prep.v5.5.0 -> obsproc_prep_RB-5.5.0
* obsproc_global.v3.4.2 -> obsproc_global_RB-3.4.2

These symlinks match nwprod obsproc package install names.

Similarly, the global-workflow develop branch config.base will use these symlinks:
* obsproc_prep.v5.5.0_hpc-stack -> obsproc_prep_RB-5.5.0_hpc-stack
* obsproc_global.v3.4.2_hpc-stack -> obsproc_global_RB-3.4.2_hpc-stack

When obsproc is using hpc-stack these hpc-stack versions will become the primary installs and the "_hpc-stack" part of the install names will be removed.

When OT tags are cut/made available from obsproc I will install those versions on supported platforms and move symlinks to point to OT installs instead of RB installs. Change should be seamless to users.

**Comment by RussTreadon-NOAA** [comment] 2021-08-18 12:37
**NCO implementation**

NCO implemented RFC 8521 just prior to 2021081806 gdas.` /gpfs/dell1/nco/ops/nwprod/versions/obsproc_global.ver` now specifies

```
## main "model" software
export obsproc_global_ver=v3.4.2

## main shared software versions

export obsproc_prep_ver=v5.5.0                   # shared PREP software
```

The EMC global dump archive `config.dumparch` needs to be updated.   There is a new dump file, `tideg.tm00.bufr_d`.    This dump file needs to be moved from `DFILES_Y` in `config.dumparch` to `DFILES`.

**Comment by KateFriedman-NOAA** [comment] 2021-08-18 13:51
The new `tideg.tm00.bufr_d` dump file is now being pulled into the GDA as part of the regular set as of 06z today:

```
.../emc/modeling/noscrub/emc.glopara/dump_archive> ll /gpfs/dell3/emc/global/dump/g*s.*0818/*/*tideg*
-rw-r--r-- 1 emc.glopara g01 1174472 Aug 18 11:50 /gpfs/dell3/emc/global/dump/gdas.20210818/06/gdas.t06z.tideg.tm00.bufr_d
```

The GDAy archival of the new TAC2BUFR files has now been discontinued.

@ShelleyMelchior-NOAA Please let me know when the OT tags have been cut for this upgrade. Thanks!

**Comment by ShelleyMelchior-NOAA** [comment] 2021-08-18 14:02
Thanks!  I will be in touch when OTs are available.  I plan to disable the cron today that supported GDAy.

**Comment by KateFriedman-NOAA** [comment] 2021-08-18 14:46
Created branch `feature/tac2bufr` for obsproc package update in develop branch. 

Updated obsproc packages in release/gfsv16.1.2.1 branch for operations branch merge. Committed at 2ca4668.

**Comment by KateFriedman-NOAA** [comment] 2021-08-19 17:07
Released tag of operations branch: https://github.com/NOAA-EMC/global-workflow/releases/tag/NCO-v16.1.2.1

**Comment by KateFriedman-NOAA** [comment] 2021-08-19 17:12
Reopening until OT tag installation is complete.

**Comment by KateFriedman-NOAA** [comment] 2021-08-19 17:12
Reopening until OT tag installation is complete.

**Comment by KateFriedman-NOAA** [comment] 2021-08-20 16:39
@ShelleyMelchior-NOAA FYI, I have saved my hpc-stack changes needed in obsproc_global and obsproc_prep in my own copies of those repositories on GitHub:

https://github.com/KateFriedman-NOAA/EMC_obsproc_global
https://github.com/KateFriedman-NOAA/EMC_obsproc_prep

I have copies of master (unchanged) in both and the recent RBs (with hpc-stack changes):
https://github.com/KateFriedman-NOAA/EMC_obsproc_global/tree/obsproc_global_RB-3.4.2
https://github.com/KateFriedman-NOAA/EMC_obsproc_prep/tree/obsproc_prep_RB-5.5.0

I successfully tested my obsproc_prep_RB-5.5.0 branch build (with hpc-stack updates) on WCOSS-Dell, Hera, Jet, and Orion. It is pretty easy to add support for new machines with these changes now (only have to add new machine check and stack paths to build.sh).

FYI, those repos are essentially "forks" of those two obsproc repos on VLab. A fork is a GitHub term meaning a copy of an authoritative/primary repo. However, since the auth obsproc repos are on VLab, my "forks" aren't connected to them like they would if the auth repo was on GitHub. Once obsproc is moved to GitHub we can use forks for real.

I'll update my forks when the OT tags come out and when the obsproc team gets to making hpc-stack updates you can use my changes as reference. Let me know if you have any questions about my changes, you can view my commit histories on these pages:

https://github.com/KateFriedman-NOAA/EMC_obsproc_global/commits/obsproc_global_RB-3.4.2
https://github.com/KateFriedman-NOAA/EMC_obsproc_prep/commits/obsproc_prep_RB-5.5.0

Note: the repo histories came in when I make my forks so you will see the other recent commits in the commit histories

**Comment by KateFriedman-NOAA** [comment] 2021-08-25 15:34
I have updated my obsproc_global and obsproc_prep fork master branches with their current states on VLab. I then added hpc-stack updates to both fork master branches and recut the OT tags from master with "-hpc-stack" in the tag names.

https://github.com/KateFriedman-NOAA/EMC_obsproc_global/releases/tag/OT-obsproc_global.v3.4.2-20210823-hpc-stack
https://github.com/KateFriedman-NOAA/EMC_obsproc_prep/releases/tag/OT-obsproc_prep.v5.5.0-20210820-hpc-stack

I have installed the new OT tags from both the VLab obsproc repos and my forks with hpc-stack updates on WCOSS-Dell (Mars and Venus). After testing the new OT tags to confirm they can reproduce prior RB branch prepbufr files I swung the symlinks to the new OT tag installs. See updated installs example on Mars:

```
[emc.glopara@m71a1 obsproc]$ pwd
/gpfs/dell2/emc/modeling/noscrub/emc.glopara/git/obsproc
[emc.glopara@m71a1 obsproc]$ ll | grep v3.4.2
lrwxrwxrwx 1 emc.glopara emcmodel  33 Aug 25 15:27 obsproc_global.v3.4.2 -> OT-obsproc_global.v3.4.2-20210823
lrwxrwxrwx 1 emc.glopara emcmodel  43 Aug 25 15:27 obsproc_global.v3.4.2_hpc-stack -> OT-obsproc_global.v3.4.2-20210823-hpc-stack
drwxr-sr-x 7 emc.glopara emcmodel 512 Aug 25 13:44 OT-obsproc_global.v3.4.2-20210823
drwxr-sr-x 7 emc.glopara emcmodel 512 Aug 25 13:50 OT-obsproc_global.v3.4.2-20210823-hpc-stack
[emc.glopara@m71a1 obsproc]$ ll | grep v5.5.0
lrwxrwxrwx 1 emc.glopara emcmodel  31 Aug 25 15:28 obsproc_prep.v5.5.0 -> OT-obsproc_prep.v5.5.0-20210820
lrwxrwxrwx 1 emc.glopara emcmodel  41 Aug 25 15:28 obsproc_prep.v5.5.0_hpc-stack -> OT-obsproc_prep.v5.5.0-20210820-hpc-stack
drwxr-sr-x 7 emc.glopara emcmodel 512 Aug 25 13:47 OT-obsproc_prep.v5.5.0-20210820
drwxr-sr-x 7 emc.glopara emcmodel 512 Aug 25 13:53 OT-obsproc_prep.v5.5.0-20210820-hpc-stack
```

Now proceeding to do the same installs and tests on Hera and Orion. Will also install hpc-stack'd OT tags on Jet for @DavidHuber-NOAA's work.

**Comment by KateFriedman-NOAA** [comment] 2021-08-25 16:03
Updated OT tags installed and tested on Hera. Symlinks updated:

```
[glopara@hfe12 obsproc]$ pwd
/scratch1/NCEPDEV/global/glopara/git/obsproc
[glopara@hfe12 obsproc]$ ll | grep v3.4.2
drwxr-sr-x  7 glopara global 4096 Aug 25 15:38 OT-obsproc_global.v3.4.2-20210823
drwxr-sr-x  7 glopara global 4096 Aug 25 15:46 OT-obsproc_global.v3.4.2-20210823-hpc-stack
lrwxrwxrwx  1 glopara global   33 Aug 25 15:58 obsproc_global.v3.4.2 -> OT-obsproc_global.v3.4.2-20210823
lrwxrwxrwx  1 glopara global   43 Aug 25 15:58 obsproc_global.v3.4.2_hpc-stack -> OT-obsproc_global.v3.4.2-20210823-hpc-stack
[glopara@hfe12 obsproc]$ ll | grep v5.5.0
drwxr-sr-x  7 glopara global 4096 Aug 25 15:43 OT-obsproc_prep.v5.5.0-20210820
drwxr-sr-x  7 glopara global 4096 Aug 25 15:45 OT-obsproc_prep.v5.5.0-20210820-hpc-stack
lrwxrwxrwx  1 glopara global   31 Aug 25 15:59 obsproc_prep.v5.5.0 -> OT-obsproc_prep.v5.5.0-20210820
lrwxrwxrwx  1 glopara global   41 Aug 25 15:59 obsproc_prep.v5.5.0_hpc-stack -> OT-obsproc_prep.v5.5.0-20210820-hpc-stack
```

**Comment by KateFriedman-NOAA** [comment] 2021-08-26 16:03
Updated OT tags installed and tested on Orion. Symlinks updated:

```
Orion-login-4[97] /work/noaa/global/glopara/git/obsproc$ pwd
/work/noaa/global/glopara/git/obsproc
Orion-login-4[98] /work/noaa/global/glopara/git/obsproc$ ll | grep v3.4.2
lrwxrwxrwx  1 kfriedma global   33 Aug 25 14:40 obsproc_global.v3.4.2 -> OT-obsproc_global.v3.4.2-20210823/
lrwxrwxrwx  1 kfriedma global   43 Aug 26 10:42 obsproc_global.v3.4.2_hpc-stack -> OT-obsproc_global.v3.4.2-20210823_hpc-stack/
drwxr-sr-x  7 kfriedma global 4096 Aug 25 10:36 OT-obsproc_global.v3.4.2-20210823/
drwxr-sr-x  7 kfriedma global 4096 Aug 25 14:37 OT-obsproc_global.v3.4.2-20210823_hpc-stack/
Orion-login-4[99] /work/noaa/global/glopara/git/obsproc$ ll | grep v5.5.0
lrwxrwxrwx  1 kfriedma global   31 Aug 26 11:01 obsproc_prep.v5.5.0 -> OT-obsproc_prep.v5.5.0-20210820/
lrwxrwxrwx  1 kfriedma global   41 Aug 26 11:01 obsproc_prep.v5.5.0_hpc-stack -> OT-obsproc_prep.v5.5.0-20210820_hpc-stack/
drwxr-sr-x  7 kfriedma global 4096 Aug 25 10:42 OT-obsproc_prep.v5.5.0-20210820/
drwxr-sr-x  7 kfriedma global 4096 Aug 25 14:34 OT-obsproc_prep.v5.5.0-20210820_hpc-stack/
```

**Comment by KateFriedman-NOAA** [comment] 2021-08-30 14:02
Updated OT tags installed on Jet. Symlinks updated to point to OT tag installs instead of RB installs:

```
.../HFIP/hfv3gfs/glopara/git/obsproc> pwd
/lfs4/HFIP/hfv3gfs/glopara/git/obsproc
[ =0 13:56:36 1039 glopara@fe1 ]
.../HFIP/hfv3gfs/glopara/git/obsproc> ll | grep v3.4.2
drwxr-sr-x 7 glopara hfv3gfs 4096 Aug 30 13:52 OT-obsproc_global.v3.4.2-20210823-hpc-stack
lrwxrwxrwx 1 glopara hfv3gfs   43 Aug 30 13:53 obsproc_global.v3.4.2_hpc-stack -> OT-obsproc_global.v3.4.2-20210823-hpc-stack
[ =0 13:56:40 1040 glopara@fe1 ]
.../HFIP/hfv3gfs/glopara/git/obsproc> ll | grep v5.5.0
drwxr-sr-x 7 glopara hfv3gfs 4096 Aug 30 13:56 OT-obsproc_prep.v5.5.0-20210820-hpc-stack
lrwxrwxrwx 1 glopara hfv3gfs   41 Aug 30 13:56 obsproc_prep.v5.5.0_hpc-stack -> OT-obsproc_prep.v5.5.0-20210820-hpc-stack
```

@DavidHuber-NOAA These are the new OT obsproc package versions as set in the develop branch after the change in ops. Your prior cycled test would have used the RB installs. I updated the symlinks (see above) with the same path you were using in your cycled testing, the results should be identical between the release branches and these final tags for the same versions. Please let me know if you encounter any issues in your cycled prep jobs or have any questions about these new installs. Thanks!

**Comment by KateFriedman-NOAA** [comment] 2021-08-30 14:03
Post-implementation installs have now been made on WCOSS-Dell, Hera, Orion, and Jet. Closing issue now.

**Closed as completed by KateFriedman-NOAA** 2021-08-30 14:03 UTC
Labels: production update
