### ISSUE TITLE
rename mom6/*/100/topo_edits_011818.nc

### ISSUE THREAD

**Issue by NeilBarton-NOAA** [NOAA-EMC/global-workflow#2812] opened 2024-08-07 13:07 UTC
### Target fix directory

mom6

### Type of change

- [X] Update existing files
- [ ] Remove files
- [ ] Add new files to existing directory
- [ ] Add new fix directory

### Any workflow changes needed?

No change needed

### Related issues

Naming convention of MOM6 topo files used by ufs is ufs.topo_edits_*.nc. This is the name in g-w scripts. However, the 100 degree fix file does not have the ufs prefix.  The ufs prfefix refers to "closing" the land at j=1 for MOM6. 

Note on hera, /scratch1/NCEPDEV/global/glopara/fix/mom6/20240416/100/topo_edits_011818.nc is the same file as the RT testing at /scratch2/NAGAPE/epic/UFS-WM_RT/NEMSfv3gfs/input-data-20240501/MOM6_FIX/100/ufs.topo_edits_011818.nc

Hence, only a name change is needed. 

### Pickup location

rename

### Size

0

**Comment by KateFriedman-NOAA** [comment] 2024-08-09 15:41
@NeilBarton-NOAA In the fix set on Hera I have renamed the file as requested. To avoid needing to make a new timestamp, since the actual file contents aren't changing, I created a symlink for the prior name to redirect as needed. Please see here on Hera and confirm it's as requested:
```
[role.glopara@hfe12 100]$ pwd
/scratch1/NCEPDEV/global/glopara/fix/mom6/20240416/100
[role.glopara@hfe12 100]$ ll | grep topo_edits
lrwxrwxrwx 1 role.glopara global       24 Aug  9 15:38 topo_edits_011818.nc -> ufs.topo_edits_011818.nc
-rw-r--r-- 1 role.glopara global     2232 Apr 13  2022 ufs.topo_edits_011818.nc
```
Will sync to other platforms once confirmed. Thanks!

**Comment by NeilBarton-NOAA** [comment] 2024-08-09 16:24
@KateFriedman-NOAA This looks good to me. Thanks

**Comment by KateFriedman-NOAA** [comment] 2024-08-09 19:52
Thanks for confirming @NeilBarton-NOAA ! I have synced the update to the fix sets on WCOSS2, Jet, AWS, and HPSS.

@WalterKolczynski-NOAA Please sync the updated `mom6/20240416` fix to Orion/Hercules, thanks!

**Comment by WalterKolczynski-NOAA** [comment] 2024-08-12 18:21
Sync'd to MSU

**Comment by KateFriedman-NOAA** [comment] 2024-08-12 18:22
Closing as complete.

**Closed as completed by KateFriedman-NOAA** 2024-08-12 18:22 UTC
Labels: Static Data Mgmt, triage
