### ISSUE TITLE
No Build Restart

### ISSUE THREAD

**Issue by TerrenceMcGuinness-NOAA** [NOAA-EMC/global-workflow#2120] opened 2023-12-04 20:30 UTC
### What new functionality do you need?

Once CI launches are done using GitHub Actions Dispatch, have one selection for restarting a PR that has been built once already and just do a Pull, and run setup_expt.py on RUNDIR/EXDIR and then start over all the CI Tests.

### What are the requirements for the new functionality?

Once moved away from Launching from READY labels we can have a drop down selector from the Dispatch Action to do the above.

### Acceptance Criteria

The functionality described above can work end-to-end from within GitHub.

**Comment by WalterKolczynski-NOAA** [comment] 2023-12-05 20:21
This looks like a duplicate of #1980

**Closed as not planned by WalterKolczynski-NOAA** 2023-12-05 20:21 UTC
Labels: duplicate, feature, CI/CD
