### ISSUE TITLE
Combine GFS and UKMET gempak scripts

### ISSUE THREAD

**Issue by WalterKolczynski-NOAA** [NOAA-EMC/global-workflow#291] opened 2021-03-12 02:16 UTC
Holly Uhlenhake 2021-03-10 19:56:29 UTC
The ukmet package produces a file for the international desk at WPC for the South American domain.  The gempak meta file is an overlay of GFS data with UKMET data.  The 00z version of this file is produced by the task ukmet_gempak_meta_sa2.sh, but the 06z file is produced by the gfs gempak script gfs_meta_sa2.sh.  The scripts are nearly identical and produce similar output.  There may have been confusion as to the origin of the file due to the combination of data involved.  We would like to have both files produced under the GFS package.  

gfs.v16.?.?/gempak/ush/gfs_meta_sa2.sh  *produces 06z meta file for South America
ukmet.v2.?.?/ush/ukmet_gfs_meta_sa2.sh  *produces 00z meta file for South America

Please work with the SPA team for the next release to consolidate these jobs since they are essentially performing the same function for different cycles.

Thanks,
Holly
SPA Team

Refs: [Bugzilla #1211](http://www2.spa.ncep.noaa.gov/bugzilla/show_bug.cgi?id=1211)

**Comment by lgannoaa** [comment] 2022-02-09 20:45
@WalterKolczynski-NOAA 
There is no such script as ukmet.v2.?.?/ush/ukmet_gfs_meta_sa2.sh
The $HOMEgfs/gempak/ush/gfs_meta_sa2.sh is the only script for this issue in question.
gfs_meta_sa2.sh contain the following:
echo " start with ukmet_gfs_meta_sa2.sh"
This echo statement shown in log file as if it is another script. This can be found in all four cycle gempak meta job log files.

This is not a bug. Because there is no issue reported for product of the gempak meta job.
You may do the following:
1. Contact SPA and have them remove this issue.
2. Contact Boi to modify script gfs_meta_sa2.sh. Modify SPA bugzilla to the root cause above.

**Comment by aerorahul** [comment] 2023-02-28 20:41
@HuiyaChuang-NOAA Can you please identify a POC for resolving this issue?

**Comment by HuiyaChuang-NOAA** [comment] 2023-02-28 21:33
> @HuiyaChuang-NOAA Can you please identify a POC for resolving this issue?

I believe Jason has in mind that his new Fed hire (announced by Brian today) will take over GFS downstream packages.
Jason will return to work next week and I will confirm this with him.

**Comment by GwenChen-NOAA** [comment] 2023-04-12 20:47
@WalterKolczynski-NOAA and @aerorahul,

While Dogwood was down yesterday, I took a closer look at the code for this issue at https://github.com/NOAA-EMC/global-workflow/blob/develop/gempak/ush/gfs_meta_sa2.sh.  If I understand the code correctly, I believe it can produce files for both 00Z and 06Z, as requested by the issue.  There was also a comment of "no issue reported for product of the gempak meta job" by lgannoaa on Feb 9, 2022.  I think this issue may be closed.  If you have other tasks in mind for this issue, please provide detailed instruction.

Thanks,
Gwen

**Comment by arunchawla-NOAA** [comment] 2023-06-15 15:07
Since we are separating out WAFS do we need this issue still ?

**Comment by GwenChen-NOAA** [comment] 2023-06-15 17:36
@Arun Chawla - NOAA Federal ***@***.***>, I don't think this
issue is related to WAFS, but it can be closed.

Gwen

**Comment by HuiyaChuang-NOAA** [comment] 2023-06-15 17:38
@arunchawla-NOAA @GwenChen-NOAA 
Gwen is right this is not related to WAFS.  WAFS does not generate gempak files

**Comment by arunchawla-NOAA** [comment] 2023-06-15 18:08
why would the global workflow create gempak files for ukmet data ?

**Comment by GwenChen-NOAA** [comment] 2023-06-15 19:11
No, global-workflow doesn't create gempak files for ukmet data.  NCO asked
us to combine GFS and UKMET gempak scripts into one script
in global-workflow, which doesn't make sense.  That's why this is not a bug
and should be closed.

Gwen

**Comment by arunchawla-NOAA** [comment] 2023-06-15 19:12
ok thanks, it makes sense. Perhaps we need to add that to bugzilla and close that

**Closed as completed** 2024-04-22 19:39 UTC
Labels: feature, nco-bug
