### ISSUE TITLE
wcoss2 transition checkout.sh - some package not clone implementation release

### ISSUE THREAD

**Issue by lgannoaa** [NOAA-EMC/global-workflow#609] opened 2022-01-27 14:36 UTC
Your bug may already be reported!
Please search on the [Issue tracker](https://github.com/NOAA-EMC/global-workflow/issues) before creating one.

**Expected behavior**

checkout.sh for wcoss2 GFS transition should checkout release tag for this implementation. 
**Current behavior**

Some package clone checked out and submodule update resulting the latest head version of the package been checkout.
This is not following the implementation code handout standard where NCO should be check out the same version as code handout (unless it is approved update).
**Machines affected**

This bug is in direct impact of wcoss2 transition implementation.
**To Reproduce**

For example in gsi.fd clone
Execute this commend:
git clone --recursive --branch gfsda.v16.2.0 https://github.com/NOAA-EMC/GSI.git gsi.fd >> ${topdir}/checkout-gsi.log 2>&1
    cd gsi.fd
git submodule update
git branch -a
  Does not show this is a implementation tag or release that has code freeze as required by implementation standard.
git log (see the software version hash been checkout and the date/comment) 
  That is not the same hash version was used in code handout.
  Is this version been approved by the NCO after the code handout as an update?
git submodule
  Will see the hash for all submodule used in this checkout.
  There are two submodule been checked out and submodule update: fix and libsrc.
  Since the package level checkout does not using a code freeze tag. Need to ensure these submodules are the same as code handout version hash. 
**Context**

Need to update each package clone within the checkout.sh to ensure it is checkout the code handout release tag and freeze the change as required by implementation rules.
**Detailed Description**

Using the above recommended solution to get all implementation tags and update the checkout.sh
**Additional Information**

No relevant information.
**Possible Implementation**

This bug impact the WCOSS2 transition implementation. Because anytime NCO run checkout.sh will be checkout the latest package instead of the approved code handout release tag.

**Comment by KateFriedman-NOAA** [comment] 2022-01-27 14:56
> Some package clone checked out and submodule update resulting the latest head version of the package been checkout.

@lgannoaa This is just simply not true. The component tags are checking out correctly in feature/ops-wcoss2. Just because it says "no branch" when you do `git branch` doesn't mean it's wrong. If you do `git log -1` you will see that it's the tag and what hash it's on. I just did a fresh clone of feature/ops-wcoss2 to illustrate my point, here is what you see in the gsi.fd folder after checkout (it's the `gfsda.v16.2.0` tag):
```
Kate.Friedman@dlogin04:/lfs/h2/emc/global/noscrub/Kate.Friedman/git/feature-ops-wcoss2_check/sorc/gsi.fd> git branch
* (no branch)
Kate.Friedman@dlogin04:/lfs/h2/emc/global/noscrub/Kate.Friedman/git/feature-ops-wcoss2_check/sorc/gsi.fd> git log -1
commit 8c9c114d9ca2fd0a3c0d54fb98ff1ee331640709 (HEAD, tag: gfsda.v16.2.0, origin/feature/gfsda.v16.1.5_wcoss2_port)
Author: michael.lueken <Michael.Lueken@noaa.gov>
Date:   Thu Jan 27 10:52:18 2022 +0000

    GitHub Issue NOAA-EMC/GSI#246. Replace COMIN_ANL with COMIN_OBS.
     * JGDAS_ENKF_DIAG - Replace COMIN_ANL with COMIN_OBS for
       * PREPQC, PREPQCPF, and NSSTBF
     * JGDAS_ENKF_SELECT_OBS - Replace COMIN_ANL with COMIN_OBS for
       * PREPQC, PREPQCPF, and NSSTBF
     * JGLOBAL_ATMOS_ANALYSIS - Replace COMOUT with COMIN_OBS for
       * NSSTBF
```

The "no branch" thing is an artifact of us consolidating the checkout command into a single line. This single line checkout method reduces the side of the component clone (because you aren't cloning two branches in the end by switching to a tag/branch after the initial clone).

Here are the other components in my fresh clone to show they are correct:
```
Kate.Friedman@dlogin04:/lfs/h2/emc/global/noscrub/Kate.Friedman/git/feature-ops-wcoss2_check/sorc/fv3gfs.fd> git branch
* (no branch)
Kate.Friedman@dlogin04:/lfs/h2/emc/global/noscrub/Kate.Friedman/git/feature-ops-wcoss2_check/sorc/fv3gfs.fd> git log -1
commit b19d750459f656664e3cbb0f2e9ce5c99b2204f2 (HEAD, tag: GFS.v16.2.0, origin/production/GFS.v16)
Author: Dusan Jovic <48258889+DusanJovic-NOAA@users.noreply.github.com>
Date:   Tue Jan 11 14:13:14 2022 -0500

    Add wcoss2 module (and module template) from NCO (#1010)
```
```
Kate.Friedman@dlogin04:/lfs/h2/emc/global/noscrub/Kate.Friedman/git/feature-ops-wcoss2_check/sorc/gldas.fd> git log -1
commit 83f51872543e51a0682c330f8b7905c2415dd8f0 (HEAD, tag: gldas_gfsv16_release.v1.25.0)
Author: HelinWei-NOAA <48133472+HelinWei-NOAA@users.noreply.github.com>
Date:   Tue Jan 18 13:57:03 2022 -0500

    Update gldas_forcing.sh
    
    Bring NCO changes from 20220118
```
```
Kate.Friedman@dlogin04:/lfs/h2/emc/global/noscrub/Kate.Friedman/git/feature-ops-wcoss2_check/sorc/ufs_utils.fd> git log -1
commit 0d09dec469637cc2c70f5795b5a5088d4838125c (HEAD, tag: ops-gfsv16.2.0)
Author: George.Gayno <george.gayno@noaa.gov>
Date:   Tue Jan 11 20:17:48 2022 +0000

    On WCOSS2, remove module purges and replace with module resets.
    
    Update library version defaults to match the build.ver
    file of gfs v16.2.
    
    Fixes #580.
```
```
Kate.Friedman@dlogin04:/lfs/h2/emc/global/noscrub/Kate.Friedman/git/feature-ops-wcoss2_check/sorc/gfs_post.fd> git log -1
commit 0168fbb0028d42d684d65ec9d4fdc524f99393f1 (HEAD, tag: upp_v8.1.0, origin/release/gfs_v16)
Author: WenMeng-NOAA <48260754+WenMeng-NOAA@users.noreply.github.com>
Date:   Tue Jan 18 14:26:25 2022 -0500

    Incorprate change from NCO (#438)
```
```
Kate.Friedman@dlogin04:/lfs/h2/emc/global/noscrub/Kate.Friedman/git/feature-ops-wcoss2_check/sorc/gfs_wafs.fd> git log -1
commit bf0f2fd87daa5ade96ed0fb13effdacfda38d10f (HEAD, tag: gfs_wafs.v6.2.7, origin/wcoss2)
Author: Yali Mao <Yali.Mao@dlogin02.dogwood.wcoss2.ncep.noaa.gov>
Date:   Wed Jan 12 20:20:35 2022 +0000

    Modified COMIN based on NCO feedback:
    1. Use ${envir} instead of '-o'
    2. Pass up to $gfs_ver, not ${RUN}.${PDY}, to compath.py
```

> Does not show this is a implementation tag or release that has code freeze as required by implementation standard.

It does. Where do you not see it cloning the tag from checkout.sh?

> Need to update each package clone within the checkout.sh to ensure it is checkout the code handout release tag and freeze the change as required by implementation rules.

This is happening. Where do you not see this happening?

> This bug is in direct impact of wcoss2 transition implementation.
> This bug impact the WCOSS2 transition implementation. Because anytime NCO run checkout.sh will be checkout the latest package instead of the approved code handout release tag.

This is not a bug. When NCO runs checkout.sh they will get the latest updated component versions that were approved, vetted, and cut by CMs. I see no issue here.

**Comment by lgannoaa** [comment] 2022-01-27 15:21
8c9c114d hash in the example as a date Thu Jan 27. It is clearly after the implementation code handout. Where is the approve from NCO to this update? gsi checkout is just an example of this bug. There are other packages checked out in similar approach.

Kate.Friedman@dlogin04:/lfs/h2/emc/global/noscrub/Kate.Friedman/git/feature-ops-wcoss2_check/sorc/gsi.fd> git log -1
commit 8c9c114d9ca2fd0a3c0d54fb98ff1ee331640709 (HEAD, tag: gfsda.v16.2.0, origin/feature/gfsda.v16.1.5_wcoss2_port)
Author: michael.lueken <Michael.Lueken@noaa.gov>
Date:   Thu Jan 27 10:52:18 2022 +0000

**Comment by KateFriedman-NOAA** [comment] 2022-01-27 15:35
> 8c9c114d hash in the example as a date Thu Jan 27. It is clearly after the implementation code handout.

Obviously...changes/fixes have been happening, you can't expect NCO to not update their testing clone during this process. This is a normal part of the implementation process, especially with regards to ports like this.

NCO has been making changes and keeping those changes local in their install. The changes that were vetted by NCO and EMC were then folded into the respective components and new/updated tags were cut. There is no other formal approval needed during this process. NCO has been fully aware of the iterative process and new tags being cut. They are currently using a dirty clone with local edits that match the latest tags of all components currently set in checkout.sh. I am double checking Wei's testing install with him today to make sure we aren't missing any updates that need to get folded in before we cut a new workflow tag.

Again, I don't see any issue here. Please illustrate an actual problem or I will close this issue shortly. Thanks!

**Comment by lgannoaa** [comment] 2022-01-27 16:02
NCO normally making changes on their local location after code delivery from test, para, to prod. EMC bring the final NCO change back to update the implementation release. NCO should be able to run checkout.sh anytime and get exact same hash as code delivered. With exception that NCO request to update a checkout tag. 
Any local modification after code delivery can not be checkout from NCO code delivery checkout.sh script without approve from NCO. Hence the reason of request this bug to be fixed.

**Comment by aerorahul** [comment] 2022-01-27 16:26
I just checked out `feature/ops-wcoss2` on WCOSS2 and here is the log out:
```
11:20 $ ./checkout.sh |& tee log
+ getopts o option
++ pwd
+ topdir=/lfs/h2/emc/stmp/Rahul.Mahajan/wcoss2port/reds/sorc
+ echo /lfs/h2/emc/stmp/Rahul.Mahajan/wcoss2port/reds/sorc
/lfs/h2/emc/stmp/Rahul.Mahajan/wcoss2port/reds/sorc
+ echo fv3gfs checkout ...
fv3gfs checkout ...
+ [[ ! -d fv3gfs.fd ]]
+ rm -f /lfs/h2/emc/stmp/Rahul.Mahajan/wcoss2port/reds/sorc/checkout-fv3gfs.log
+ git clone --recursive --branch GFS.v16.2.0 https://github.com/ufs-community/ufs-weather-model.git fv3gfs.fd
+ cd /lfs/h2/emc/stmp/Rahul.Mahajan/wcoss2port/reds/sorc
+ echo gsi checkout ...
gsi checkout ...
+ [[ ! -d gsi.fd ]]
+ rm -f /lfs/h2/emc/stmp/Rahul.Mahajan/wcoss2port/reds/sorc/checkout-gsi.log
+ git clone --branch gfsda.v16.2.0 https://github.com/NOAA-EMC/GSI.git gsi.fd
+ cd gsi.fd
/lfs/h2/emc/stmp/Rahul.Mahajan/wcoss2port/reds/sorc/gsi.fd
+ git submodule update
+ cd /lfs/h2/emc/stmp/Rahul.Mahajan/wcoss2port/reds/sorc
+ echo gldas checkout ...
gldas checkout ...
+ [[ ! -d gldas.fd ]]
+ rm -f /lfs/h2/emc/stmp/Rahul.Mahajan/wcoss2port/reds/sorc/checkout-gldas.log
+ git clone --branch gldas_gfsv16_release.v1.25.0 https://github.com/NOAA-EMC/GLDAS gldas.fd
+ cd /lfs/h2/emc/stmp/Rahul.Mahajan/wcoss2port/reds/sorc
+ echo ufs_utils checkout ...
ufs_utils checkout ...
+ [[ ! -d ufs_utils.fd ]]
+ rm -f /lfs/h2/emc/stmp/Rahul.Mahajan/wcoss2port/reds/sorc/checkout-ufs_utils.log
+ git clone --branch ops-gfsv16.2.0 https://github.com/ufs-community/UFS_UTILS ufs_utils.fd
+ cd /lfs/h2/emc/stmp/Rahul.Mahajan/wcoss2port/reds/sorc
+ echo EMC_post checkout ...
EMC_post checkout ...
+ [[ ! -d gfs_post.fd ]]
+ rm -f /lfs/h2/emc/stmp/Rahul.Mahajan/wcoss2port/reds/sorc/checkout-gfs_post.log
+ git clone --branch upp_v8.1.0 https://github.com/NOAA-EMC/UPP.git gfs_post.fd
+ checkout_gtg=NO
+ [[ NO == \Y\E\S ]]
+ cd /lfs/h2/emc/stmp/Rahul.Mahajan/wcoss2port/reds/sorc
+ echo EMC_gfs_wafs checkout ...
EMC_gfs_wafs checkout ...
+ [[ ! -d gfs_wafs.fd ]]
+ rm -f /lfs/h2/emc/stmp/Rahul.Mahajan/wcoss2port/reds/sorc/checkout-gfs_wafs.log
+ git clone --recursive --branch gfs_wafs.v6.2.7 https://github.com/NOAA-EMC/EMC_gfs_wafs.git gfs_wafs.fd
+ cd /lfs/h2/emc/stmp/Rahul.Mahajan/wcoss2port/reds/sorc
+ echo EMC_verif-global checkout ...
EMC_verif-global checkout ...
+ [[ ! -d verif-global.fd ]]
+ rm -f /lfs/h2/emc/stmp/Rahul.Mahajan/wcoss2port/reds/sorc/checkout-verif-global.log
+ git clone --recursive --branch verif_global_v1.11.0 https://github.com/NOAA-EMC/EMC_verif-global.git verif-global.fd
+ cd /lfs/h2/emc/stmp/Rahul.Mahajan/wcoss2port/reds/sorc
+ exit 0
```

I did disable recursive checkout of gsi, since I don't have vlab set up on WCOSS2.

Inspecting the directories randomly, I see the correct hashes for the tags that are in `checkout.sh`.

**Closed as completed by aerorahul** 2022-01-27 16:26 UTC
Labels: bug
